Repository ampproject/amp-wp, pull requests merged in 2018-07, with the labels that each got.

#1207 Add caching of redirect to non-AMP URL when validation errors present
  includes/class-amp-theme-support.php
  includes/validation/class-amp-validation-manager.php
  tests/test-class-amp-theme-support.php
Labels: beta

#1274 Convert video src to HTTPS
  includes/sanitizers/class-amp-video-sanitizer.php
  tests/test-amp-video-sanitizer.php
Labels: [Type] Bug

#1287 Report removing unrecognized elements.
  includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php
  tests/test-tag-and-attribute-sanitizer.php
Labels: [Type] Bug

#1289 Opt-in to CORS mode for external font stylesheet links
  includes/sanitizers/class-amp-style-sanitizer.php
  tests/test-amp-style-sanitizer.php
Labels: pwa
