Repository ampproject/amp-wp, pull requests merged in 2018-08, with the labels that each got.

#1293 Fix displaying AMP validation error at block level in the Gutenberg editor
  assets/js/amp-block-validation.js
  assets/src/amp-block-editor-toggle.js
Labels: [Type] Bug

#1320 Improve handling of !important transformation specificity
  includes/sanitizers/class-amp-style-sanitizer.php
  tests/test-amp-style-sanitizer.php
Labels: [Type] Bug, css

#1321 Filter the attachment image attributes for the Twenty Seventeen theme.
  includes/sanitizers/class-amp-core-theme-sanitizer.php
Labels: [Type] Bug

#1281 [WIP] Fix wide image to contain in content
  includes/sanitizers/class-amp-img-sanitizer.php
  tests/test-amp-img-sanitizer.php
Labels: [Type] Bug

#1338 Use all eligible post types when `all_templates_supported` is selected.
  includes/options/class-amp-options-manager.php
  tests/test-class-amp-options-manager.php
Labels: [Type] Bug

#1325 Improve post processor response cache
  includes/class-amp-theme-support.php
  includes/options/class-amp-options-manager.php
  includes/options/class-amp-options-menu.php
  tests/test-class-amp-options-manager.php
  tests/test-class-amp-theme-support.php
Labels: [Type] Bug

#1315 Update spec generation to file revision 712 (amphtml tag 1533692711873)
  bin/amphtml-update.py
  includes/sanitizers/class-amp-allowed-tags-generated.php
  includes/sanitizers/class-amp-rule-spec.php
  includes/sanitizers/class-amp-style-sanitizer.php
  includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php
  tests/amp-tag-and-attribute-sanitizer-private-methods-tests.php
  tests/test-tag-and-attribute-sanitizer.php
Labels: release

#1375 Display when validation results are stale due to active theme/plugin changes
  includes/validation/class-amp-invalid-url-post-type.php
  tests/validation/test-class-amp-invalid-url-post-type.php
Labels: Compatability Tool
