Repository ampproject/amp-wp, pull requests merged in 2020-11, with the labels that each got.

#5556 Use patches from GitHub to patch PHP-CSS-Parser
  Gruntfile.js
  composer.json
  composer.lock
  patches/php-css-parser-commit-10a2501.patch
  patches/php-css-parser-pull-185.patch
  patches/php-css-parser-pull-193.patch
Labels: WS:Core, dependencies

#5571 Fix CS issue in external library
  lib/common/src/Url.php
Labels: Tech Debt

#5201 Run tests via GitHub Actions
  .dev-lib
  .github/workflows/build-test-measure.yml
  .travis.yml
  bin/ci/after-wp-install.sh
  bin/ci/install-wp-tests.sh
  bin/install-wp-tests.sh
  bin/local-env/includes.sh
  bin/local-env/install-composer.sh
  bin/local-env/install-node-nvm.sh
  composer.json
  composer.lock
  package.json
  tests/php/bootstrap.php
  tests/php/test-amp-helper-functions.php
  tests/php/test-class-amp-reader-themes-rest-controller.php
Labels: Infrastructure, Testing, WS:Core, cla: yes

#5583 Update CI status badge in readme
  .editorconfig
  .github/workflows/build-test-measure.yml
  readme.md
Labels: WS:Core

#5584 Add /vendor to testPathIgnorePatterns for JS unit tests
  tests/js/jest.config.js
Labels: WS:Core

#5599 Fix Travis issues on 2.0 branch
  .travis.yml
  tests/php/test-amp-helper-functions.php
Labels: WS:Core

#5568 Add support for Composer v2
  .github/workflows/build-test-measure.yml
  composer.lock
Labels: Infrastructure, WS:Core, dependencies

#5601 Add Composer v2 support for v2.0 of plugin
  .github/workflows/build-test-measure.yml
  .travis.yml
  composer.json
  composer.lock
  lib/common/composer.json
  lib/optimizer/composer.json
Labels: Infrastructure, WS:Core, dependencies

#5610 Downgrade Composer to v1 in v2.0 of plugin
  .github/workflows/build-test-measure.yml
  .travis.yml
  composer.json
  composer.lock
  lib/common/composer.json
  lib/optimizer/composer.json
Labels: WS:Core

#5608 Update AMP validator spec to 2011140244000
  assets/src/block-editor/helpers/index.js
  bin/ci/after-wp-install.sh
  includes/sanitizers/class-amp-allowed-tags-generated.php
  tests/php/test-tag-and-attribute-sanitizer.php
  tests/php/validation/test-class-amp-validation-manager.php
Labels: WS:Core

#5341 Update Codecov configuration
  codecov.yml
  phpunit.xml.dist
Labels: Infrastructure, WS:Core, cla: yes

#5306 Refactor URL validation CLI script to make parts reusable
  composer.lock
  includes/cli/class-amp-cli-validation-command.php
  src/Validation/ScannableURLProvider.php
  src/Validation/URLValidationProvider.php
  tests/php/src/Helpers/ValidationRequestMocking.php
  tests/php/src/Validation/ScannableURLProviderTest.php
  tests/php/src/Validation/URLValidationProviderTest.php
  tests/php/static-analysis-stubs/wp-cli.php
  tests/php/test-class-amp-cli-validation-command.php
Labels: Validation, WS:UX, cla: yes
