Repository ampproject/amp-wp, pull requests merged in 2020-08, with the labels that each got.

#5133 Allow any active plugin to be suppressed
  assets/src/settings-page/plugin-suppression.js
  assets/src/settings-page/style.css
  src/PluginSuppression.php
  tests/php/src/OptionsRESTControllerTest.php
  tests/php/src/PluginSuppressionTest.php
Labels: Changelogged, cla: yes

#5142 Prevent printing the request-filesystem-credentials-form in the head
  src/Admin/ReaderThemes.php
Labels: Bug, cla: yes

#5143 Make sure submit_button() function exists before calling fs_connect() in ReaderThemes::can_install_theme()
  src/Admin/ReaderThemes.php
Labels: Bug, cla: yes

#5144 Prevent scoping total error index count in admin menu
  includes/validation/class-amp-validation-error-taxonomy.php
  tests/php/validation/test-class-amp-validation-error-taxonomy.php
Labels: cla: yes

#5149 Update copy in last step of onboarding flow
  assets/src/onboarding-wizard/pages/save/index.js
Labels: cla: yes

#5151 Close output buffer in addition to cleaning after calling fs_connect
  src/Admin/ReaderThemes.php
Labels: Bug, cla: yes

#5157 Allow boolean attributes to repeat repeat attribute name as attribute value
  includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php
  tests/php/src/Helpers/MarkupComparison.php
  tests/php/test-tag-and-attribute-sanitizer.php
Labels: cla: yes

#5158 Improve styling of Plugin Suppression table
  assets/src/settings-page/plugin-suppression.js
  assets/src/settings-page/style.css
Labels: cla: yes

#5150 Add garbage collection of stylesheet information from URLs validated over a week ago
  includes/validation/class-amp-validated-url-post-type.php
  src/AmpWpPlugin.php
  src/BackgroundTask/CronBasedBackgroundTask.php
  src/BackgroundTask/ValidatedUrlStylesheetDataGarbageCollection.php
  tests/php/src/ValidatedUrlStylesheetDataGarbageCollectionTest.php
  tests/php/validation/test-class-amp-validated-url-post-type.php
  tests/php/validation/test-class-amp-validation-manager.php
Labels: cla: yes

#5153 Move amp_is_enabled filter to amp_bootstrap_plugin()
  amp.php
  includes/amp-helper-functions.php
  src/PluginSuppression.php
  tests/php/src/PluginSuppressionTest.php
  tests/php/test-amp-helper-functions.php
  tests/php/test-amp.php
Labels: cla: yes

#5155 Add Analytics option to settings screen
  assets/src/components/amp-drawer/style.css
  assets/src/components/amp-notice/style.css
  assets/src/components/amp-setting-toggle/style.css
  assets/src/components/reader-theme-carousel/index.js
  assets/src/components/selectable/style.css
  assets/src/components/template-mode-option/style.css
  assets/src/components/theme-card/index.js
  assets/src/components/theme-card/style.css
  assets/src/css/elements.css
  assets/src/css/variables.css
  assets/src/onboarding-wizard/style.css
  assets/src/settings-page/analytics.js
  assets/src/settings-page/index.js
  assets/src/settings-page/settings-footer.js
  assets/src/settings-page/style.css
  assets/src/settings-page/template-modes.js
  includes/amp-helper-functions.php
  includes/options/class-amp-analytics-options-submenu.php
  includes/options/class-amp-options-manager.php
  includes/options/views/class-amp-analytics-options-submenu-page.php
  package-lock.json
  package.json
  src/Admin/OptionsMenu.php
  src/OptionsRESTController.php
  tests/e2e/specs/admin/analytics-options.js
  tests/e2e/specs/amp-onboarding/reader-themes.js
  tests/php/src/Admin/OptionsMenuTest.php
  tests/php/src/OptionsRESTControllerTest.php
  tests/php/test-amp-analytics-options.php
  tests/php/test-class-amp-options-manager.php
Labels: cla: yes

#5170 Settings screen: switch to legacy if selected reader theme is active site theme
  assets/src/components/reader-themes-context-provider/index.js
Labels: cla: yes

#5164 Improve handling of polyfilled assets (and improve handling of Reader themes data)
  Gruntfile.js
  includes/admin/class-amp-template-customizer.php
  includes/amp-helper-functions.php
  includes/class-amp-theme-support.php
  src/Admin/OnboardingWizardSubmenuPage.php
  src/Admin/OptionsMenu.php
  src/Admin/Polyfills.php
  src/Admin/RESTPreloader.php
  src/Admin/ReaderThemes.php
  src/AmpWpPlugin.php
  tests/php/src/Admin/GoogleFontsTest.php
  tests/php/src/Admin/PolyfillsTest.php
  webpack.config.js
Labels: cla: yes

#5195 Rename is_amp_available() as amp_is_available()
  includes/admin/class-amp-template-customizer.php
  includes/amp-helper-functions.php
  includes/validation/class-amp-validation-manager.php
  src/MobileRedirection.php
  tests/php/src/MobileRedirectionTest.php
  tests/php/test-amp-helper-functions.php
Labels: cla: yes

#5196 Indicate reviewed status when viewing an individual validation error
  assets/css/src/amp-validation-error-taxonomy.css
  includes/validation/class-amp-validated-url-post-type.php
  includes/validation/class-amp-validation-error-taxonomy.php
  tests/php/validation/test-class-amp-validation-error-taxonomy.php
Labels: cla: yes

#5197 Prevent finishing initialization if not on frontend
  includes/class-amp-theme-support.php
Labels: WS:Core, cla: yes

#5159 Fallback to AMP Legacy Reader theme if active Reader theme is unavailable
  assets/src/components/phone/style.css
  assets/src/components/reader-themes-context-provider/__mocks__/index.js
  assets/src/components/reader-themes-context-provider/index.js
  assets/src/components/svg/desktop-icon.svg
  assets/src/components/svg/mobile-icon.svg
  assets/src/components/theme-card/index.js
  assets/src/components/theme-card/style.css
  assets/src/onboarding-wizard/components/nav/index.js
  assets/src/onboarding-wizard/components/nav/test/index.js
  assets/src/onboarding-wizard/pages/summary/desktop-screenshot.js
  assets/src/onboarding-wizard/pages/summary/reader.js
  assets/src/onboarding-wizard/pages/summary/style.css
  assets/src/onboarding-wizard/style.css
  assets/src/settings-page/style.css
  includes/amp-helper-functions.php
  includes/options/class-amp-options-manager.php
  package-lock.json
  src/Admin/OnboardingWizardSubmenuPage.php
  src/Admin/OptionsMenu.php
  src/Admin/ReaderThemes.php
  src/Infrastructure/ServiceBasedPlugin.php
  src/OptionsRESTController.php
  src/ReaderThemeLoader.php
  tests/e2e/specs/amp-onboarding/template-mode.js
  tests/js/jest.config.js
  tests/php/data/themes/child-of-core/style.css
  tests/php/src/Admin/ReaderThemesTest.php
  tests/php/src/Helpers/LoadsCoreThemes.php
  tests/php/src/ReaderThemeLoaderTest.php
  tests/php/test-amp-gallery-embed-handler.php
  tests/php/test-amp-helper-functions.php
  tests/php/test-amp-style-sanitizer.php
  tests/php/test-class-amp-core-theme-sanitizer.php
  tests/php/test-class-amp-options-manager.php
  tests/php/test-class-amp-reader-themes-rest-controller.php
  tests/php/test-class-amp-template-customizer.php
  tests/php/test-includes-admin-functions.php
  tests/php/validation/test-class-amp-validated-url-post-type.php
Labels: cla: yes

#5194 Use UI font for mobile version switcher link
  templates/style.php
Labels: WS:UX, cla: yes

#5198 Ensure paired browsing template_include filter overrides other filters
  includes/class-amp-theme-support.php
Labels: Bug, WS:Core, cla: yes

#5192 Improve font sizes in onboarding wizard and settings screen
  assets/src/components/amp-info/style.css
  assets/src/components/amp-setting-toggle/style.css
  assets/src/components/selectable/style.css
  assets/src/components/template-mode-option/style.css
  assets/src/components/theme-card/style.css
  assets/src/css/core-components.css
  assets/src/css/elements.css
  assets/src/onboarding-wizard/components/nav/index.js
  assets/src/onboarding-wizard/components/nav/test/index.js
  assets/src/onboarding-wizard/pages/summary/style.css
  assets/src/onboarding-wizard/style.css
  assets/src/settings-page/plugin-suppression.js
  assets/src/settings-page/style.css
  assets/src/settings-page/welcome.js
  tests/e2e/specs/amp-onboarding/done.js
Labels: cla: yes

#5199 Add analytics vendor type checking; rewrite docs in details
  assets/src/settings-page/analytics.js
  assets/src/settings-page/style.css
Labels: cla: yes

#5200 Improve amp-analytics guidance when googleanalytics is selected
  assets/src/settings-page/analytics.js
  assets/src/settings-page/index.js
  assets/src/settings-page/style.css
Labels: cla: yes

#5212 Make homepage, description, and name all optional fields for Reader themes
  assets/src/components/theme-card/index.js
  src/Admin/ReaderThemes.php
Labels: WS:UX, cla: yes

#5211 Wizard: move close button to the top in mobile view
  assets/src/common/constants.js
  assets/src/components/carousel/index.js
  assets/src/components/reader-theme-carousel/index.js
  assets/src/css/core-components.css
  assets/src/onboarding-wizard/components/nav/index.js
  assets/src/onboarding-wizard/setup-wizard.js
  assets/src/onboarding-wizard/style.css
  assets/src/utils/use-window-width.js
  tests/e2e/specs/amp-onboarding/close-button.js
Labels: cla: yes

#5202 Abort AMP post-processing if an expected template actions are not triggered
  includes/class-amp-theme-support.php
  tests/php/test-amp-style-sanitizer.php
  tests/php/test-class-amp-theme-support.php
Labels: Bug, cla: yes

#5214 Ensure non-AMP link in paired browsing does not redirect to AMP version
  assets/src/admin/paired-browsing/app.js
  includes/class-amp-theme-support.php
  includes/templates/amp-paired-browsing.php
Labels: Bug, cla: yes

#5203 Defer mobile redirection to end of template_redirect action
  src/MobileRedirection.php
  tests/php/src/MobileRedirectionTest.php
Labels: Bug, WS:Core, cla: yes

#5219 Amend amp_get_current_url() to return null if the home URL cannot be parsed in CLI environment
  includes/amp-helper-functions.php
  tests/e2e/specs/amp-onboarding/template-mode.js
  tests/php/test-amp-helper-functions.php
Labels: WS:Core, cla: yes

#5217 Eliminate regex used to determine if content from output buffer is a valid HTML document since done actions now used
  includes/class-amp-theme-support.php
  tests/php/test-class-amp-theme-support.php
Labels: WS:Core, cla: yes

#5231 Fix typos in deprecation comments
  includes/amp-helper-functions.php
Labels: Documentation, WS:Core, cla: yes

#5216 Add link to analytics options in submenu and make all settings sections linkable
  assets/src/components/amp-drawer/index.js
  assets/src/components/carousel/index.js
  assets/src/settings-page/analytics.js
  assets/src/settings-page/index.js
  assets/src/settings-page/mobile-redirection.js
  assets/src/settings-page/plugin-suppression.js
  assets/src/settings-page/style.css
  assets/src/settings-page/supported-templates.js
  assets/src/settings-page/template-modes.js
  includes/options/class-amp-options-manager.php
  src/Admin/AnalyticsOptionsSubmenu.php
  src/Admin/OptionsMenu.php
  src/Admin/Polyfills.php
  src/AmpWpPlugin.php
  tests/e2e/specs/admin/analytics-options.js
  tests/e2e/specs/admin/anchor-linking.js
  tests/e2e/specs/admin/reader-theme-carousel.js
  tests/e2e/utils/visit-admin-page-with-hash.js
  tests/php/src/Admin/AnalyticsOptionsSubmenuTest.php
  tests/php/src/Admin/OptionsMenuTest.php
  tests/php/validation/test-class-amp-validated-url-post-type.php
  tests/php/validation/test-class-amp-validation-error-taxonomy.php
Labels: WS:UX, cla: yes

#5235 Reduce top/bottom padding in wizard nav bar
  assets/src/onboarding-wizard/components/nav/style.css
Labels: WS:UX, cla: yes

#5230 Add extra "AMP" header for themes to indicate their support for AMP
  assets/src/components/reader-theme-carousel/style.css
  assets/src/components/reader-theme-selection/style.css
  includes/class-amp-theme-support.php
  src/Admin/ReaderThemes.php
  src/AmpWpPlugin.php
  src/ExtraThemeAndPluginHeaders.php
  tests/php/data/themes/child-of-core/style.css
  tests/php/data/themes/with-legacy/amp/meta-author.php
  tests/php/data/themes/with-legacy/style.css
  tests/php/src/Admin/ReaderThemesTest.php
  tests/php/src/ExtraThemeAndPluginHeadersTest.php
  tests/php/test-class-amp-reader-themes-rest-controller.php
Labels: WS:Core, cla: yes

#5237 Filter `sslverify` value when performing validation loopback request
  includes/validation/class-amp-validation-manager.php
Labels: WS:Core, cla: yes

#5224 Fix warnings that occur during PHP testing with coverage
  tests/php/src/Admin/GoogleFontsTest.php
  tests/php/src/Admin/OnboardingWizardSubmenuPageTest.php
  tests/php/src/Admin/OnboardingWizardSubmenuTest.php
  tests/php/src/Admin/OptionsMenuTest.php
  tests/php/src/Admin/PluginActivationNoticeTest.php
  tests/php/src/Admin/PolyfillsTest.php
  tests/php/src/Admin/RESTPreloaderTest.php
  tests/php/src/Admin/ReaderThemesTest.php
  tests/php/src/AmpSlugCustomizationWatcherTest.php
  tests/php/src/IconTest.php
  tests/php/src/MobileRedirectionTest.php
  tests/php/src/ObsoleteBlockAttributeRemoverTest.php
  tests/php/src/OptionsRESTControllerTest.php
  tests/php/src/PluginRegistryTest.php
  tests/php/src/PluginSuppressionTest.php
  tests/php/src/ReaderThemeLoaderTest.php
  tests/php/src/ValidatedUrlStylesheetDataGarbageCollectionTest.php
  tests/php/test-class-amp-schema-org-metadata.php
  tests/php/test-class-dev-tools-user-access.php
  tests/php/test-class-monitor-css-transient-caching.php
  tests/php/test-wp-http-remote-get-request.php
  tests/php/validation/test-class-amp-validated-url-post-type.php
Labels: WS:Core, cla: yes

#5248 Replace focus selector with a common class selector when used in a descendant combinator
  includes/sanitizers/class-amp-style-sanitizer.php
  tests/php/test-amp-style-sanitizer.php
  tests/php/validation/test-class-amp-validation-manager.php
Labels: WS:Core, cla: yes

#5243 Only show fatal errors on Validated URL screen when WP_DEBUG_DISPLAY is enabled
  includes/validation/class-amp-validated-url-post-type.php
  includes/validation/class-amp-validation-manager.php
Labels: WS:Core, cla: yes

#5259 Add missing @internal tag to function in bootstrap file
  amp.php
Labels: Documentation, WS:Core, cla: yes

#5260 Annotate AnalyticsOptionsSubmenu class as internal
  src/Admin/AnalyticsOptionsSubmenu.php
Labels: Documentation, WS:Core, cla: yes

#5261 Add missing internal tags on deprecated code
  includes/amp-frontend-actions.php
  includes/amp-helper-functions.php
  includes/class-amp-autoloader.php
  includes/class-amp-comment-walker.php
  includes/class-amp-http.php
  includes/class-amp-post-type-support.php
  includes/deprecated.php
  includes/embeds/class-amp-youtube-embed-handler.php
  includes/sanitizers/class-amp-base-sanitizer.php
  includes/templates/class-amp-content.php
  includes/utils/class-amp-dom-utils.php
  includes/widgets/class-amp-widget-archives.php
  includes/widgets/class-amp-widget-categories.php
  includes/widgets/class-amp-widget-text.php
Labels: Documentation, WS:Core, cla: yes

#5262 Update link to analytics documentation
  assets/src/settings-page/analytics.js
Labels: WS:Core, cla: yes

#5255 Fix layout of mobile version switcher in core themes
  assets/css/src/amp-mobile-version-switcher.css
  src/MobileRedirection.php
  templates/style.php
Labels: WS:Core, cla: yes

#5266 Remove checkbox column from error index since bulk actions removed
  assets/css/src/amp-validation-error-taxonomy.css
  includes/validation/class-amp-validation-error-taxonomy.php
  tests/php/validation/test-class-amp-validation-error-taxonomy.php
Labels: Bug, Developer Tools, WS:Core, cla: yes

#5263 Reverse style traversal when turning sizes attribute into CSS
  lib/optimizer/src/Transformer/ServerSideRendering.php
  lib/optimizer/tests/Transformer/ServerSideRenderingTest.php
Labels: Bug, Optimizer, WS:Perf, cla: yes

#5258 Legacy Customizer: Remove AMP toggle bind to mobile preview; default to tablet preview
  assets/src/customizer/amp-customize-controls-legacy.js
Labels: WS:Core, cla: yes

#5267 Fix validation of amp-bodymovin-animation loop attribute
  includes/sanitizers/class-amp-allowed-tags-generated.php
  tests/php/test-tag-and-attribute-sanitizer.php
Labels: cla: yes

#5269 Remove unused REMOVED_SOURCES constant
  includes/validation/class-amp-validation-error-taxonomy.php
Labels: Tech Debt, WS:Core, cla: yes

#5270 Prevent wp_print_service_workers() from happening at wp_print_footer_scripts in legacy Reader mode
  includes/class-amp-service-worker.php
  tests/php/test-class-amp-service-worker.php
Labels: Bug, Integration: PWA, WS:Core, cla: yes

#5265 Settings screen: allow showing success notice multiple times
  assets/src/components/amp-notice/index.js
  assets/src/components/options-context-provider/index.js
  assets/src/settings-page/index.js
  assets/src/settings-page/style.css
Labels: WS:UX, cla: yes

#5273 Avoid version lock-in for libs for now
  composer.json
  lib/common/composer.json
  lib/optimizer/composer.json
Labels: Infrastructure, WS:Core, cla: yes

#5160 Update readme with new content for the plugin page
  readme.md
  readme.txt
  wp-assets/banner-1544x500.png
  wp-assets/banner-772x250.png
  wp-assets/icon-128x128.png
  wp-assets/icon-256x256.png
  wp-assets/screenshot-1.png
  wp-assets/screenshot-10.png
  wp-assets/screenshot-11.png
  wp-assets/screenshot-12.png
  wp-assets/screenshot-13.png
  wp-assets/screenshot-2.png
  wp-assets/screenshot-3.png
  wp-assets/screenshot-4.png
  wp-assets/screenshot-5.png
  wp-assets/screenshot-6.png
  wp-assets/screenshot-7.png
  wp-assets/screenshot-8.png
  wp-assets/screenshot-9.png
Labels: WS:Core, cla: yes

#5280 Fix iframe height on done screen of onboarding wizard
  assets/src/onboarding-wizard/pages/save/style.css
Labels: WS:UX, cla: yes

#5284 Hide Customizer panel collapse button label and improve positioning of AMP toggle
  assets/css/src/amp-customizer-legacy.css
  assets/src/customizer/amp-customize-controls-legacy.js
Labels: cla: yes

#5283 Fix supplying schema for options endpoint
  src/OptionsRESTController.php
Labels: cla: yes

#5282 Print amp-default.css via amp_post_template_css action instead of in style.php template
  includes/amp-helper-functions.php
  includes/amp-post-template-functions.php
  includes/class-amp-theme-support.php
  templates/style.php
Labels: Bug, CSS, Reader Mode, WS:Core, cla: yes

#5294 Ensure AMP_QUERY_VAR is defined for plugins that expect it
  includes/amp-helper-functions.php
Labels: cla: yes
