Repository ampproject/amp-wp, pull requests merged in 2020-01, with the labels that each got.

#4025 Quick tiny fix: update input types
  assets/src/edit-story/panels/backgroundColor.js
  assets/src/edit-story/panels/color.js
  assets/src/edit-story/panels/font.js
  assets/src/edit-story/panels/text.js
Labels: cla: yes

#4009 Fix handling of gallery carousels in paragraphs and fix no-JS fallbacks
  includes/embeds/class-amp-gallery-embed.php
  src/Component/Carousel.php
  tests/php/test-amp-carousel.php
  tests/php/test-amp-gallery-embed.php
  tests/php/test-class-amp-gallery-block-sanitizer.php
Labels: Type: Bug, cla: yes

#4027 Fix commas being saved to content
  assets/src/edit-story/app/story/actions/useSavePost.js
Labels: cla: yes

#4008 Reset edit state when a new element is selected to avoid nested loop
  assets/src/edit-story/components/canvas/page.js
Labels: cla: yes

#4010 Switch click and pointerdown to mousedown and prevent unselection
  assets/src/edit-story/components/canvas/canvasLayout.js
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/element.js
  assets/src/edit-story/components/canvas/page.js
  assets/src/edit-story/components/movable/index.js
  assets/src/edit-story/elements/image/display.js
  assets/src/edit-story/elements/text/display.js
Labels: Stories, cla: yes

#3957 Create a separate layer for all Moveable instances
  assets/src/edit-story/components/canvas/page.js
  assets/src/edit-story/components/movable/context.js
  assets/src/edit-story/components/movable/index.js
  assets/src/edit-story/components/movable/movableLayer.js
  assets/src/edit-story/components/selection/index.js
Labels: Stories, cla: yes

#4033 Switch click and pointerdown to mousedown and prevent unselection
  assets/src/edit-story/components/canvas/canvasLayout.js
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/element.js
  assets/src/edit-story/components/canvas/page.js
  assets/src/edit-story/components/movable/index.js
  assets/src/edit-story/elements/image/display.js
  assets/src/edit-story/elements/text/display.js
Labels: cla: yes

#4007 Tiny fix: refocus the editor when the wrapper is clicked
  assets/src/edit-story/elements/text/edit.js
Labels: Stories, cla: yes

#3964 Cropped image editor
  assets/src/edit-story/app/index.js
  assets/src/edit-story/components/movable/cropStyle.js
  assets/src/edit-story/elements/image/edit.js
  assets/src/edit-story/elements/image/editCropMovable.js
  assets/src/edit-story/elements/image/editPanMovable.js
  assets/src/edit-story/elements/image/util.js
  package-lock.json
  package.json
Labels: Stories, cla: yes

#4029 Update wp-dev-lib package
  .dev-lib
  composer.json
  composer.lock
  tests/php/test-class-amp-imgur-embed-handler.php
Labels: cla: yes

#4045 Fix ability to update the status of a validation error
  includes/validation/class-amp-validated-url-post-type.php
  includes/validation/class-amp-validation-manager.php
  tests/php/validation/test-class-amp-validation-manager.php
Labels: cla: yes

#4018 Selection canvas with lasso
  assets/src/edit-story/app/story/actions/useSetPropertiesOnSelectedElements.js
  assets/src/edit-story/app/story/storyProvider.js
  assets/src/edit-story/components/canvas/canvasLayout.js
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/element.js
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/page.js
  assets/src/edit-story/components/canvas/selection.js
  assets/src/edit-story/components/canvas/selectionCanvas.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/canvas/useEditingElement.js
  assets/src/edit-story/components/movable/index.js
  assets/src/edit-story/components/movable/movableLayer.js
  assets/src/edit-story/components/overlay/context.js
  assets/src/edit-story/components/overlay/index.js
  assets/src/edit-story/components/overlay/withOverlay.js
  assets/src/edit-story/elements/image/display.js
  assets/src/edit-story/elements/image/edit.js
  assets/src/edit-story/elements/shared.js
  assets/src/edit-story/elements/square/display.js
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/video/display.js
  assets/src/edit-story/theme.js
Labels: Stories, cla: yes

#4053 Update amp-instagram embed regex
  includes/embeds/class-amp-instagram-embed.php
  tests/php/test-amp-instagram-embed.php
Labels: cla: yes

#4051 Update amp-video embed regex pattern
  includes/embeds/class-amp-vimeo-embed.php
  tests/php/test-amp-vimeo-embed.php
Labels: cla: yes

#3998 Font picker
  amp.php
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/font/actions/useLoadFontFiles.js
  assets/src/edit-story/app/font/context.js
  assets/src/edit-story/app/font/effects/useLoadFonts.js
  assets/src/edit-story/app/font/fontProvider.js
  assets/src/edit-story/app/font/index.js
  assets/src/edit-story/app/font/useFont.js
  assets/src/edit-story/app/index.js
  assets/src/edit-story/components/library/textLibrary.js
  assets/src/edit-story/elements/shared.js
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/elements/text/save.js
  assets/src/edit-story/elements/text/util.js
  assets/src/edit-story/panels/font.js
  assets/src/edit-story/panels/shared.js
  includes/class-amp-autoloader.php
  includes/class-amp-fonts.php
  includes/class-amp-story-legacy-post-type.php
  includes/class-amp-story-post-type.php
  includes/rest-api/class-amp-rest-fonts-controller.php
Labels: Stories, cla: yes

#4043 Ignore Story editor tests
  .travis.yml
  bin/local-env/run-e2e-tests.js
  tests/e2e/jest.config.js
  tests/e2e/specs/block-editor/featured-image-notice.js
Labels: cla: yes

#4073 Missing file
  assets/src/edit-story/components/inspector/shared.js
Labels: Stories, cla: yes

#4044 Copy/paste for selected elements inside the canvas
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/useCanvasSelectionCopyPaste.js
  assets/src/edit-story/elements/image/index.js
  assets/src/edit-story/elements/image/textContent.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/elements/text/textContent.js
  assets/src/edit-story/utils/useClipboardHandlers.js
Labels: Stories, cla: yes

#4105 Preserve styles applied via [style] attribute selectors
  includes/sanitizers/class-amp-style-sanitizer.php
  tests/php/test-amp-audio-converter.php
  tests/php/test-amp-script-sanitizer.php
  tests/php/test-amp-style-sanitizer.php
Labels: CSS, cla: yes

#4034 Attempt to fix test__multiple_valid_image_files
  tests/php/test-amp-image-dimension-extractor.php
Labels: cla: yes

#4107 Preserve leading comments to main HTML elements
  src/Dom/Document.php
  tests/php/test-amp-audio-converter.php
  tests/php/test-class-amp-dom-document.php
  tests/php/test-tag-and-attribute-sanitizer.php
Labels: cla: yes

#4108 Group dragging and rotating.
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/panels/font.js
  assets/src/edit-story/panels/shared.js
Labels: Stories, cla: yes

#4049 Page navigation
  assets/src/edit-story/components/button/icon_left_arrow.svg
  assets/src/edit-story/components/button/icon_right_arrow.svg
  assets/src/edit-story/components/button/index.js
  assets/src/edit-story/components/canvas/canvasLayout.js
  assets/src/edit-story/components/canvas/pagenav/index.js
  assets/src/edit-story/constants.js
Labels: Stories, cla: yes

#4005 New page meta bar
  assets/src/edit-story/components/canvas/addpage/index.js
  assets/src/edit-story/components/canvas/addpage/plus.svg
  assets/src/edit-story/components/canvas/canvasLayout.js
  assets/src/edit-story/components/canvas/meta/delete.svg
  assets/src/edit-story/components/canvas/meta/duplicate.svg
  assets/src/edit-story/components/canvas/meta/index.js
  assets/src/edit-story/components/canvas/pagemenu/add_page.svg
  assets/src/edit-story/components/canvas/pagemenu/delete_icon.svg
  assets/src/edit-story/components/canvas/pagemenu/duplicate_icon.svg
  assets/src/edit-story/components/canvas/pagemenu/index.js
  assets/src/edit-story/components/canvas/pagemenu/layout_helper.svg
  assets/src/edit-story/components/canvas/pagemenu/redo_icon.svg
  assets/src/edit-story/components/canvas/pagemenu/text_helper.svg
  assets/src/edit-story/components/canvas/pagemenu/undo_icon.svg
  assets/src/edit-story/components/header/buttons.js
  assets/src/edit-story/components/switch/index.js
  assets/src/edit-story/elements/index.js
  assets/src/edit-story/theme.js
Labels: Stories, cla: yes

#4004 Don't mock HTTP requests for the external-http testsuite
  .travis.yml
  phpunit.xml
  tests/php/test-amp-crowdsignal-embed-handler.php
  tests/php/test-amp-image-dimension-extract-download.php
  tests/php/test-amp-image-dimension-extractor.php
  tests/php/test-amp-scribd-embed-handler.php
  tests/php/test-amp-soundcloud-embed-handler.php
  tests/php/test-amp-twitter-embed-handler.php
  tests/php/test-class-amp-gfycat-embed-handler.php
  tests/php/test-class-amp-hulu-embed-handler.php
  tests/php/test-class-amp-imgur-embed-handler.php
  tests/php/test-class-amp-wordpress-tv-embed-handler.php
  tests/php/test-class-amp-youtube-embed-handler.php
  tests/php/validation/test-class-amp-validated-url-post-type.php
Labels: cla: yes

#4013 A floating scaling panel
  assets/src/edit-story/constants.js
  assets/src/edit-story/elements/image/edit.js
  assets/src/edit-story/elements/image/scalePanel.js
  assets/src/edit-story/theme.js
  assets/src/edit-story/utils/useClipboardHandlers.js
Labels: Stories, cla: yes

#4120 reshuffled grid areas and cleaned up some styles
  assets/src/edit-story/app/layout/index.js
  assets/src/edit-story/components/button/index.js
  assets/src/edit-story/components/canvas/canvasLayout.js
  assets/src/edit-story/components/header/buttons.js
  assets/src/edit-story/components/header/headerLayout.js
  assets/src/edit-story/components/header/title.js
  assets/src/edit-story/constants.js
  assets/src/edit-story/theme.js
Labels: Stories, cla: yes

#4140 Load roboto the old fashioned way.
  includes/class-amp-story-post-type.php
Labels: cla: yes

#4141 Basic color
  assets/src/edit-story/components/library/shapeLibrary.js
  assets/src/edit-story/elements/square/index.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/panels/backgroundColor.js
  assets/src/edit-story/panels/color.js
Labels: cla: yes

#4142 Add basic min / max font size.
  assets/src/edit-story/panels/font.js
  assets/src/edit-story/panels/shared.js
Labels: Stories, cla: yes

#4122 First pass at document sidebar
  assets/src/edit-story/app/api/apiProvider.js
  assets/src/edit-story/app/story/actions/useDeleteStory.js
  assets/src/edit-story/app/story/actions/useSaveStory.js
  assets/src/edit-story/app/story/effects/useHistoryEntry.js
  assets/src/edit-story/app/story/effects/useHistoryReplay.js
  assets/src/edit-story/app/story/effects/useLoadStory.js
  assets/src/edit-story/app/story/storyProvider.js
  assets/src/edit-story/app/story/useStoryReducer/actions.js
  assets/src/edit-story/app/story/useStoryReducer/reducers/restore.js
  assets/src/edit-story/app/story/useStoryReducer/test/restore.js
  assets/src/edit-story/app/story/useStoryReducer/useStoryReducer.js
  assets/src/edit-story/components/header/buttons.js
  assets/src/edit-story/components/header/title.js
  assets/src/edit-story/components/inspector/documentInspector.js
  assets/src/edit-story/components/inspector/inspectorContent.js
  assets/src/edit-story/components/inspector/inspectorProvider.js
  assets/src/edit-story/components/inspector/shared.js
  assets/src/edit-story/components/library/mediaLibrary.js
  assets/src/edit-story/components/uploadButton/index.js
  includes/class-amp-story-post-type.php
  includes/rest-api/class-amp-rest-stories-controller.php
Labels: Stories, cla: yes

#4125 Text element: resizing & fit text feature
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/constants.js
  assets/src/edit-story/elements/text/save.js
  assets/src/edit-story/elements/text/util.js
  assets/src/edit-story/panels/font.js
  assets/src/edit-story/panels/shared.js
  assets/src/edit-story/utils/calculateFitTextFontSize.js
  assets/src/edit-story/utils/getAdjustedElementDimensions.js
Labels: Stories, cla: yes

#4143 Make all strings translatable
  assets/src/edit-story/app/font/fontProvider.js
  assets/src/edit-story/components/canvas/pagenav/index.js
  assets/src/edit-story/components/header/buttons.js
  assets/src/edit-story/components/header/title.js
  assets/src/edit-story/components/inspector/documentInspector.js
  assets/src/edit-story/components/inspector/inspectorTabs.js
  assets/src/edit-story/components/inspector/prepublishInspector.js
  assets/src/edit-story/components/inspector/shared.js
  assets/src/edit-story/components/library/linkLibrary.js
  assets/src/edit-story/components/library/mediaLibrary.js
  assets/src/edit-story/components/library/shapeLibrary.js
  assets/src/edit-story/components/library/textLibrary.js
  assets/src/edit-story/components/uploadButton/index.js
  assets/src/edit-story/elements/image/scalePanel.js
  assets/src/edit-story/elements/index.js
  assets/src/edit-story/panels/actions.js
  assets/src/edit-story/panels/backgroundColor.js
  assets/src/edit-story/panels/color.js
  assets/src/edit-story/panels/font.js
  assets/src/edit-story/panels/fullbleed.js
  assets/src/edit-story/panels/position.js
  assets/src/edit-story/panels/rotationAngle.js
  assets/src/edit-story/panels/scale.js
  assets/src/edit-story/panels/shared.js
  assets/src/edit-story/panels/size.js
  assets/src/edit-story/panels/text.js
Labels: Stories, cla: yes

#4106 Rework page carousel
  assets/src/edit-story/app/layout/index.js
  assets/src/edit-story/components/button/icons/arrow_left.svg
  assets/src/edit-story/components/button/icons/arrow_right.svg
  assets/src/edit-story/components/button/icons/grid_view.svg
  assets/src/edit-story/components/button/icons/redo.svg
  assets/src/edit-story/components/button/icons/undo.svg
  assets/src/edit-story/components/button/index.js
  assets/src/edit-story/components/canvas/canvasLayout.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/carrousel/index.js
  assets/src/edit-story/components/canvas/pagenav/index.js
  assets/src/edit-story/components/inspector/inspectorTabs.js
  assets/src/edit-story/components/library/libraryLayout.js
  assets/src/edit-story/constants.js
  assets/src/edit-story/theme.js
  package-lock.json
  package.json
Labels: Stories, cla: yes

#4148 More translations
  assets/src/edit-story/panels/rotationAngle.js
  assets/src/edit-story/panels/scale.js
  assets/src/edit-story/panels/size.js
Labels: Stories, cla: yes

#4150 Add missing npm dependency
  package-lock.json
  package.json
Labels: Integration: Gutenberg, cla: yes

#4048 Page reordering from carousel
  assets/src/edit-story/app/layout/index.js
  assets/src/edit-story/components/canvas/canvasLayout.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/dropzone/context.js
  assets/src/edit-story/components/dropzone/dropZoneProvider.js
  assets/src/edit-story/components/dropzone/index.js
  assets/src/edit-story/components/dropzone/useDropZone.js
Labels: Stories, cla: yes

#4159 Update readme to add FAQs section
  readme.md
  readme.txt
Labels: cla: yes

#4154 Hide carousel arrows when scrolling to end
  assets/src/edit-story/components/canvas/carousel/index.js
Labels: Stories, cla: yes

#4155 Add group resizing.
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
Labels: Stories, cla: yes

#4165 Fix: Add height to dropzoneprovider div.
  assets/src/edit-story/components/dropzone/dropZoneProvider.js
Labels: Stories, cla: yes

#4151 Text element: text-align, letter-spacing, line-height, padding
  assets/src/edit-story/elements/shared.js
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/edit.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/elements/text/save.js
  assets/src/edit-story/panels/index.js
  assets/src/edit-story/panels/shared.js
  assets/src/edit-story/panels/style.js
Labels: Stories, cla: yes

#4164 Prevent validation error for WordPress.tv embed in Classic Editor
  includes/embeds/class-amp-wordpress-tv-embed-handler.php
  tests/php/test-class-amp-wordpress-tv-embed-handler.php
Labels: cla: yes

#4163 Address notice and console error in Paired Browsing from async
  includes/class-amp-theme-support.php
  tests/php/test-class-amp-theme-support.php
Labels: cla: yes

#4129 Preview: reimplement workspace layering
  assets/src/edit-story/app/layout/index.js
  assets/src/edit-story/components/canvas/canvasLayout.js
  assets/src/edit-story/components/canvas/canvasProvider.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/displayElement.js
  assets/src/edit-story/components/canvas/displayLayer.js
  assets/src/edit-story/components/canvas/editElement.js
  assets/src/edit-story/components/canvas/editLayer.js
  assets/src/edit-story/components/canvas/frameElement.js
  assets/src/edit-story/components/canvas/framesLayer.js
  assets/src/edit-story/components/canvas/index.js
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/components/canvas/multiSelectionMovable.js
  assets/src/edit-story/components/canvas/navLayer.js
  assets/src/edit-story/components/canvas/page.js
  assets/src/edit-story/components/canvas/pagemenu/index.js
  assets/src/edit-story/components/canvas/pagenav/index.js
  assets/src/edit-story/components/canvas/selectionCanvas.js
  assets/src/edit-story/components/canvas/singleSelectionMovable.js
  assets/src/edit-story/components/canvas/useTransformHandler.js
  assets/src/edit-story/components/movable/index.js
  assets/src/edit-story/components/overlay/index.js
  assets/src/edit-story/elements/image/display.js
  assets/src/edit-story/elements/image/frame.js
  assets/src/edit-story/elements/image/index.js
  assets/src/edit-story/elements/image/scalePanel.js
  assets/src/edit-story/elements/image/util.js
  assets/src/edit-story/elements/text/display.js
  assets/src/edit-story/elements/text/frame.js
  assets/src/edit-story/elements/text/index.js
  assets/src/edit-story/theme.js
  assets/src/edit-story/utils/pointerEventsCss.js
Labels: Stories, cla: yes

#4146 Allow opting-out of AMP-to-AMP links, ensure 'Exit Reader Mode' link is non-AMP
  includes/amp-helper-functions.php
  includes/sanitizers/class-amp-link-sanitizer.php
  templates/header-bar.php
  tests/php/test-amp-helper-functions.php
  tests/php/test-class-amp-link-sanitizer.php
Labels: cla: yes

#4166 Prevent validation errors for URLs with leading or trailing spaces
  includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php
  tests/php/test-amp-tag-and-attribute-sanitizer-private-methods.php
Labels: cla: yes

#4170 Move header to the canvas area
  assets/src/edit-story/app/layout/index.js
  assets/src/edit-story/components/canvas/layout.js
  assets/src/edit-story/components/canvas/navLayer.js
  assets/src/edit-story/components/header/headerLayout.js
  assets/src/edit-story/components/header/title.js
Labels: cla: yes

#4171 Upgrade to react-moveable:0.16.6
  package-lock.json
  package.json
Labels: Stories, cla: yes

#4153 Grid View Modal
  assets/src/edit-story/app/index.js
  assets/src/edit-story/components/canvas/carousel/index.js
  assets/src/edit-story/components/canvas/draggablePage.js
  assets/src/edit-story/components/canvas/gridview/index.js
  assets/src/edit-story/components/canvas/gridview/rectangle.svg
  assets/src/edit-story/components/dropzone/dropZoneProvider.js
  assets/src/edit-story/components/dropzone/index.js
  assets/src/edit-story/components/modal/index.js
  assets/src/edit-story/index.js
  package-lock.json
  package.json
Labels: Stories, cla: yes

#4026 Add stylesheet information to validated URL screen
  assets/css/src/admin-tables.css
  assets/css/src/amp-validation-error-taxonomy.css
  assets/src/amp-validation/amp-validated-url-post-edit-screen.js
  includes/amp-helper-functions.php
  includes/class-amp-autoloader.php
  includes/class-amp-story-post-type.php
  includes/class-amp-theme-support.php
  includes/cli/class-amp-cli-validation-command.php
  includes/options/class-amp-options-manager.php
  includes/sanitizers/class-amp-base-sanitizer.php
  includes/sanitizers/class-amp-style-sanitizer.php
  includes/templates/class-amp-content-sanitizer.php
  includes/validation/class-amp-validated-url-post-type.php
  includes/validation/class-amp-validation-error-taxonomy.php
  includes/validation/class-amp-validation-manager.php
  tests/php/stubs.php
  tests/php/test-amp-style-sanitizer.php
  tests/php/test-class-amp-content-sanitizer.php
  tests/php/validation/test-class-amp-validated-url-post-type.php
  tests/php/validation/test-class-amp-validation-manager.php
Labels: cla: yes

#4180 Fix E2E tests on 1.4 branch
  composer.json
  composer.lock
  package-lock.json
  package.json
Labels: cla: yes

#4185 Avoid entering The Loop when rendering Reader template
  includes/templates/reader-template-loader.php
Labels: Type: Bug, cla: yes

#4184 Redirect to non-AMP version when making non-singular AMP request; prevent using Reader mode template for Stories
  includes/class-amp-theme-support.php
  tests/php/test-class-amp-theme-support.php
Labels: Type: Bug, cla: yes

#4181 Parse malformed [meta charset] tag
  includes/class-amp-theme-support.php
  src/Dom/Document.php
  tests/php/test-tag-and-attribute-sanitizer.php
Labels: cla: yes

#4111 Fix invalid layout on non-AMP elements
  includes/sanitizers/class-amp-layout-sanitizer.php
  tests/php/test-amp-layout-sanitizer.php
Labels: cla: yes

#4193 Convert `head[profile]` attribute to `link[rel=profile]`
  src/Dom/Document.php
  tests/php/test-class-amp-dom-document.php
Labels: cla: yes

#4194 Conditionally remove html[xmlns], convert html[xml:lang] to html[lang]
  src/Dom/Document.php
  tests/php/test-class-amp-dom-document.php
Labels: cla: yes

#4207 Prevent errors in admin bar filters from non-array arguments
  includes/class-amp-theme-support.php
  tests/php/test-class-amp-theme-support.php
Labels: cla: yes

#4205 Split Reader mode style template part stylesheet from action-supplied styles
  includes/sanitizers/class-amp-style-sanitizer.php
  templates/html-start.php
Labels: CSS, cla: yes
