Repository ampproject/amp-wp, pull requests merged in 2020-12, with the labels that each got.

#5656 Update ataylorme/eslint-annotate-action to v1.1.2
  .github/workflows/build-test-measure.yml
Labels: WS:Core, dependencies

#5637 [2.0] Allow for tests to be run on PHP 8
  .dev-lib
  .travis.yml
  composer.json
  lib/optimizer/resources/local_fallback/rtv/metadata
  lib/optimizer/resources/local_fallback/v0.css
  lib/optimizer/tests/SpecTest.php
  lib/optimizer/tests/spec/end-to-end/body-only/expected_output.default.html
  lib/optimizer/tests/spec/end-to-end/body-only/expected_output.lts.html
  lib/optimizer/tests/spec/end-to-end/hello-world/expected_output.default.html
  lib/optimizer/tests/spec/end-to-end/hello-world/expected_output.lts.html
  lib/optimizer/tests/spec/end-to-end/hello-world/expected_output.paired.html
  lib/optimizer/tests/spec/end-to-end/story/expected_output.default.html
  lib/optimizer/tests/spec/end-to-end/story/expected_output.lts.html
  lib/optimizer/tests/spec/end-to-end/story/expected_output.paired.html
  lib/optimizer/tests/spec/transformers/experimental/AddBlurryImagePlaceholders/adds_blurry_placeholders_where_needed/expected_output.html
  lib/optimizer/tests/spec/transformers/experimental/AddBlurryImagePlaceholders/adds_blurry_placeholders_where_needed/input.html
  lib/optimizer/tests/spec/transformers/experimental/ServerSideRendering/transforms_layout_intrinsic/expected_output.html
  lib/optimizer/tests/spec/transformers/experimental/ServerSideRendering/transforms_layout_intrinsic/input.html
  lib/optimizer/tests/spec/transformers/valid/MinifyHtml/minifies_inline_amp-script/expected_output.html
  lib/optimizer/tests/spec/transformers/valid/PreloadHeroImage/srcset_cannot_be_preloaded/expected_output.html
  lib/optimizer/tests/spec/transformers/valid/PreloadHeroImage/srcset_cannot_be_preloaded/input.html
  lib/optimizer/tests/spec/transformers/valid/ServerSideRendering/converts_heights_attribute_to_css/expected_output.html
  lib/optimizer/tests/spec/transformers/valid/ServerSideRendering/converts_sizes_attribute_to_css/expected_output.html
  lib/optimizer/tests/spec/transformers/valid/ServerSideRendering/does_not_convert_invalid_heights_attribute/expected_output.html
  lib/optimizer/tests/spec/transformers/valid/ServerSideRendering/does_not_convert_invalid_sizes_attribute/expected_output.html
  lib/optimizer/tests/spec/transformers/valid/ServerSideRendering/transforms_layout_responsive/expected_output.html
  lib/optimizer/tests/src/MarkupComparison.php
  tests/php/src/DevTools/CallbackReflectionTest.php
  tests/php/test-amp-crowdsignal-embed-handler.php
Labels: WS:Core

#5663 Eliminate redundant legacy method of adding Schema.org metadata
  includes/amp-post-template-functions.php
  tests/php/test-amp-helper-functions.php
Labels: Schema.org Metadata, WS:Core

#5648 Add support for the Twenty Twenty-One theme
  assets/images/reader-themes/legacy.jpg
  assets/images/reader-themes/twentyeleven.jpg
  assets/images/reader-themes/twentyfifteen.jpg
  assets/images/reader-themes/twentyfourteen.jpg
  assets/images/reader-themes/twentynineteen.jpg
  assets/images/reader-themes/twentyseventeen.jpg
  assets/images/reader-themes/twentysixteen.jpg
  assets/images/reader-themes/twentythirteen.jpg
  assets/images/reader-themes/twentytwelve.jpg
  assets/images/reader-themes/twentytwenty.jpg
  assets/images/reader-themes/twentytwentyone.jpg
  includes/admin/class-amp-template-customizer.php
  includes/amp-post-template-functions.php
  includes/sanitizers/class-amp-core-theme-sanitizer.php
  phpstan.neon.dist
  src/Admin/ReaderThemes.php
  tests/e2e/specs/amp-onboarding/reader-themes.js
  tests/php/test-amp-post-template-functions.php
  tests/php/test-class-amp-core-theme-sanitizer.php
  tests/php/test-class-amp-reader-themes-rest-controller.php
  tests/php/test-class-amp-template-customizer.php
Labels: WS:Core

#5680 Update Twenty Twenty-One mobile screenshot; make notice about dark mode toggle clearer; fix mobile switcher link on non-AMP
  assets/images/reader-themes/twentytwentyone.jpg
  includes/admin/class-amp-template-customizer.php
  includes/sanitizers/class-amp-core-theme-sanitizer.php
  src/MobileRedirection.php
  tests/php/src/MobileRedirectionTest.php
Labels: Changelogged, WS:Core

#5669 Remove unused NPM dependencies
  package-lock.json
  package.json
  postcss.config.js
Labels: WS:Core, dependencies

#5690 Add export exclusions to gitattributes file
  .gitattributes
Labels: Bug, Integration: Web Stories, P0

#5573 Hide AMP Layout control if block does not have specified setting
  assets/src/block-editor/helpers/index.js
  assets/src/block-editor/helpers/test/AmpLayoutControl.js
Labels: Editor, WS:Core

#5574 Hide AMP Noloading toggle if block does not have specified setting
  assets/src/block-editor/helpers/index.js
  assets/src/block-editor/helpers/test/AmpNoloadingToggle.js
Labels: WS:Core

#5670 Set php and js coverage threshold to 0.1%
  codecov.yml
Labels: WS:Core

#5694 Improve diff output for PHP files
  .gitattributes
Labels: WS:Core

#5692 Replace amp-lightbox with an amp-bind solution for the mobile menu in Twenty Twenty-One
  includes/sanitizers/class-amp-core-theme-sanitizer.php
  package.json
  tests/php/test-class-amp-core-theme-sanitizer.php
Labels: Bug, WS:Core

#5699 Persist focus on mobile menu button when toggling
  includes/sanitizers/class-amp-core-theme-sanitizer.php
Labels: WS:Core

#5647 Feature/5611 : Adding filters for featured image minimum height and width
  assets/src/common/components/select-media-frame.js
  assets/src/common/constants.js
  assets/src/common/helpers/index.js
  assets/src/common/helpers/test/__mocks__/amp-block-editor-data.js
  assets/src/common/helpers/test/getMinimumFeaturedImageDimensions.js
  assets/src/common/helpers/test/hasMinimumDimensions.js
  assets/src/common/helpers/test/validateFeaturedImage.js
  includes/admin/class-amp-post-meta-box.php
  tests/php/test-class-amp-meta-box.php
Labels: Editor, WS:Core

#5705 Disable lazy-loading during AMP_Scribd_Embed_Handler_Test for WP 5.7-alpha
  tests/php/test-amp-scribd-embed-handler.php
Labels: Testing, WS:Core

#5704 Catch InvalidService exception when amp_is_available() is called before plugins_loaded
  includes/amp-helper-functions.php
Labels: WS:Core

#5657 Update PWA plugin API calls for v0.6
  includes/class-amp-service-worker.php
  tests/php/static-analysis-stubs/pwa.php
Labels: Integration: PWA, WS:Core

#5722 Deprecate obsolete amp_post_template_add_analytics_script()
  includes/amp-post-template-functions.php
  includes/deprecated.php
  tests/php/test-amp-post-template-functions.php
Labels: Tech Debt, WS:Core

#5720 Close Twenty Twenty and Twenty Twenty-One mobile menus when clicking on in-page anchor link menu items
  includes/sanitizers/class-amp-core-theme-sanitizer.php
  tests/php/test-class-amp-core-theme-sanitizer.php
Labels: WS:Core

#5730 Fix attempting to echo and escape _ex()
  includes/admin/class-amp-template-customizer.php
Labels: WS:Core

#5732 Eliminate no-global-event-listener ESLint warnings
  assets/src/amp-validation/amp-validated-url-post-edit-screen.js
  assets/src/amp-validation/amp-validation-single-error-url-details.js
  assets/src/components/unsaved-changes-warning/index.js
  assets/src/mobile-redirection.js
  assets/src/onboarding-wizard/index.js
  assets/src/onboarding-wizard/setup-wizard.js
  assets/src/settings-page/index.js
  assets/src/utils/use-window-width.js
Labels: WS:UX

#5742 Add phpcs checks with WordPress-VIP-Go ruleset
  .phpcs.xml.dist
  composer.json
  composer.lock
  includes/admin/class-amp-post-meta-box.php
  includes/amp-helper-functions.php
  includes/class-amp-http.php
  includes/class-amp-theme-support.php
  includes/cli/class-amp-cli-validation-command.php
  includes/sanitizers/class-amp-form-sanitizer.php
  includes/validation/class-amp-validated-url-post-type.php
  includes/validation/class-amp-validation-error-taxonomy.php
  includes/validation/class-amp-validation-manager.php
  src/BackgroundTask/MonitorCssTransientCaching.php
  src/DevTools/UserAccess.php
  src/MobileRedirection.php
  src/ReaderThemeLoader.php
Labels: Tech Debt, WS:Core

#5743 Fix parsing of docblocks that contain code snippets
  composer.json
  composer.lock
  docs/src/Parser/Parser.php
  docs/templates/function.mustache
  includes/amp-helper-functions.php
Labels: Documentation, WS:Core

#5747 Only run PHPStan (on all PHP files) in pre-commit hook if there is a modified PHP file
  .github/workflows/build-test-measure.yml
  .lintstagedrc.js
  composer.json
  package.json
Labels: Testing, WS:Core

#5515 Create background events for URL validation
  .phpstorm.meta.php
  docs/class/README.md
  docs/class/Validation/ScannableURLProvider.md
  docs/class/Validation/URLValidationProvider.md
  docs/method/README.md
  docs/method/Validation/ScannableURLProvider/__construct.md
  docs/method/Validation/ScannableURLProvider/get_urls.md
  docs/method/Validation/URLValidationProvider/get_number_validated.md
  docs/method/Validation/URLValidationProvider/get_total_errors.md
  docs/method/Validation/URLValidationProvider/get_unaccepted_errors.md
  docs/method/Validation/URLValidationProvider/get_url_validation.md
  docs/method/Validation/URLValidationProvider/get_validity_by_type.md
  docs/method/Validation/URLValidationProvider/is_locked.md
  docs/method/Validation/URLValidationProvider/reset_lock.md
  docs/method/Validation/URLValidationProvider/with_lock.md
  includes/cli/class-amp-cli-validation-command.php
  src/AmpWpPlugin.php
  src/BackgroundTask/BackgroundTaskDeactivator.php
  src/BackgroundTask/CronBasedBackgroundTask.php
  src/BackgroundTask/MonitorCssTransientCaching.php
  src/BackgroundTask/RecurringBackgroundTask.php
  src/BackgroundTask/SingleScheduledBackgroundTask.php
  src/BackgroundTask/ValidatedUrlStylesheetDataGarbageCollection.php
  src/Validation/SavePostValidationEvent.php
  src/Validation/ScannableURLProvider.php
  src/Validation/URLScanningContext.php
  src/Validation/URLValidationCron.php
  src/Validation/URLValidationProvider.php
  tests/php/src/BackgroundTask/BackgroundTaskDeactivatorTest.php
  tests/php/src/BackgroundTask/MonitorCssTransientCachingTest.php
  tests/php/src/ValidatedUrlStylesheetDataGarbageCollectionTest.php
  tests/php/src/Validation/SavePostValidationEventTest.php
  tests/php/src/Validation/ScannableURLProviderTest.php
  tests/php/src/Validation/URLScanningContextTest.php
  tests/php/src/Validation/URLValidationCronTest.php
  tests/php/src/Validation/URLValidationProviderTest.php
Labels: WS:UX

#5754 Remove E2E test utils that are now available upstream
  .github/workflows/build-test-measure.yml
  tests/e2e/config/bootstrap.js
  tests/e2e/specs/admin/amp-options.js
  tests/e2e/specs/amp-onboarding/template-mode.js
  tests/e2e/specs/block-editor/amp-preview-button.js
  tests/e2e/specs/block-editor/amp-toggle.js
  tests/e2e/utils/activate-plugin.js
  tests/e2e/utils/activate-theme.js
  tests/e2e/utils/deactivate-plugin.js
  tests/e2e/utils/delete-theme.js
  tests/e2e/utils/index.js
  tests/e2e/utils/install-theme.js
  tests/e2e/utils/theme-installed.js
Labels: Testing, WS:Core

#5755 [2.0] Remove E2E test utils that are now available upstream
  package-lock.json
  package.json
  tests/e2e/config/bootstrap.js
  tests/e2e/specs/admin/amp-options.js
  tests/e2e/specs/amp-onboarding/template-mode.js
  tests/e2e/specs/block-editor/amp-preview-button.js
  tests/e2e/specs/block-editor/amp-toggle.js
  tests/e2e/utils/activate-plugin.js
  tests/e2e/utils/activate-theme.js
  tests/e2e/utils/deactivate-plugin.js
  tests/e2e/utils/delete-theme.js
  tests/e2e/utils/index.js
  tests/e2e/utils/install-theme.js
  tests/e2e/utils/theme-installed.js
Labels: Testing, WS:Core
