Repository ampproject/amp-wp, pull requests merged in 2021-06, with the labels that each got.

#6347 Fix condition preventing Gutenberg packages PR from being created
  .github/workflows/gutenberg-packages-update.yml
Labels: Infrastructure

#6349 Remove newlines from package list before setting step output
  .github/workflows/gutenberg-packages-update.yml
Labels: Infrastructure

#6380 Close latest Gutenberg packages update PR if it is outdated
  .github/workflows/gutenberg-packages-update.yml
Labels: Infrastructure

#6379 Remove dependency approve list from `auto-merge` workflow
  .github/workflows/auto-merge.yml
Labels: Infrastructure

#6378 Allow for required GHA job statuses to be reported so that all PR checks have a status
  .github/workflows/build-test-measure.yml
  .github/workflows/qa-integrate.yml
  bin/determine-modified-files-count.php
Labels: Infrastructure

#6393 Fix path regex for QA plugin workflow
  .github/workflows/qa-integrate.yml
Labels: Infrastructure

#6396 Check for `conflicts.user` property before rendering list item
  .github/workflows/build-test-measure.yml
  assets/src/settings-page/paired-url-structure.js
Labels: Bug

#6397 [2.1] Update codecov GitHub Action
  .github/workflows/build-test-measure.yml
Labels: Infrastructure

#6398 Update class name used to display a pending state when retrieving validation counts
  assets/src/amp-validation/counts/index.js
  assets/src/amp-validation/counts/style.css
  includes/validation/class-amp-validated-url-post-type.php
  includes/validation/class-amp-validation-error-taxonomy.php
  tests/php/validation/test-class-amp-validated-url-post-type.php
  tests/php/validation/test-class-amp-validation-error-taxonomy.php
Labels: Bug

#6400 Trigger CI jobs when a dependency file is modified
  .github/workflows/build-test-measure.yml
  .github/workflows/qa-integrate.yml
Labels: Infrastructure

#6403 Ensure site icon in legacy template is identified as a hero image
  templates/header-bar.php
Labels: Optimizer, Performance

#6401 Fix GHA job that closes stale Gutenberg update PRs
  .github/workflows/gutenberg-packages-update.yml
Labels: Infrastructure

#6320 Add error boundary to the Settings page
  .phpstorm.meta.php
  assets/src/amp-validation/counts/index.js
  assets/src/amp-validation/counts/style.css
  assets/src/components/clipboard-button/index.js
  assets/src/components/clipboard-button/test/__snapshots__/index.js.snap
  assets/src/components/clipboard-button/test/index.js
  assets/src/components/error-boundary/index.js
  assets/src/components/error-screen/index.js
  assets/src/components/error-screen/style.css
  assets/src/components/error-screen/test/__snapshots__/index.js.snap
  assets/src/components/error-screen/test/index.js
  assets/src/components/site-settings-provider/index.js
  assets/src/css/core-components.css
  assets/src/onboarding-wizard/index.js
  assets/src/settings-page/index.js
  includes/validation/class-amp-validated-url-post-type.php
  includes/validation/class-amp-validation-error-taxonomy.php
  src/Admin/OnboardingWizardSubmenuPage.php
  src/Admin/OptionsMenu.php
  src/AmpWpPlugin.php
  src/LoadingError.php
  tests/php/src/Admin/AnalyticsOptionsSubmenuTest.php
  tests/php/src/Admin/OnboardingWizardSubmenuPageTest.php
  tests/php/src/Admin/OptionsMenuTest.php
  tests/php/src/LoadingErrorTest.php
  tests/php/validation/test-class-amp-validated-url-post-type.php
  tests/php/validation/test-class-amp-validation-error-taxonomy.php
Labels: Bug, Enhancement, WS:UX

#6425 Update amphtml spec to 2106240350000
  includes/sanitizers/class-amp-allowed-tags-generated.php
  tests/php/test-tag-and-attribute-sanitizer.php
Labels: Validation

#6434 Fix test_get_mu_plugins_data for WP 5.8
  tests/php/src/PluginRegistryTest.php
Labels: Testing

#6435 Update hero image handling to remove max count
  composer.json
  composer.lock
  src/Cli/TransformerCommand.php
  src/Optimizer/AmpWPConfiguration.php
  src/Optimizer/Transformer/DetermineHeroImages.php
  tests/php/src/Optimizer/AmpWPConfigurationTest.php
  tests/php/src/Optimizer/Transformer/DetermineHeroImagesTest.php
Labels: Optimizer, Performance

#6439 Update automerge workflow to use PAT
  .github/workflows/auto-merge.yml
Labels: Infrastructure

#6440 Ensure first entry content in DetermineHeroImages matches amp-wp-article-content in legacy Reader templates
  src/Optimizer/Transformer/DetermineHeroImages.php
  tests/php/src/Optimizer/Transformer/DetermineHeroImagesTest.php
Labels: Optimizer, Reader Mode
