Repository ampproject/amp-wp, pull requests merged in 2021-09, with the labels that each got.

#6589 Introduce `transform_important_qualifiers` arg to `AMP_Style_Sanitizer`
  includes/sanitizers/class-amp-style-sanitizer.php
  tests/php/test-amp-style-sanitizer.php
Labels: CSS, Bento

#6423 Preserve seek time and other parameters to `amp-youtube` from YouTube embeds
  .github/workflows/build-test-measure.yml
  includes/embeds/class-amp-base-embed-handler.php
  includes/embeds/class-amp-youtube-embed-handler.php
  includes/utils/class-amp-dom-utils.php
  includes/validation/class-amp-validation-error-taxonomy.php
  src/BackgroundTask/MonitorCssTransientCaching.php
  tests/php/test-class-amp-youtube-embed-handler.php
Labels: Embeds

#6591 Add CodeQL GHA to find potential security vulnerabilities
  .github/workflows/codeql-analysis.yml
Labels: Infrastructure

#6592 Ensure only a single instance of a workflow using the same concurrency group will run at a time
  .github/workflows/auto-merge.yml
  .github/workflows/build-test-measure.yml
  .github/workflows/cancel-previous-runs.yml
  .github/workflows/gutenberg-packages-update.yml
Labels: Infrastructure

#6554 Update Gutenberg packages after v11.4.1 release
  package-lock.json
  package.json
  webpack.config.js
Labels: dependencies

#6608 Fix LGTM code analysis warnings
  .github/workflows/codeql-analysis.yml
  assets/src/admin/paired-browsing/client.js
  assets/src/block-editor/components/layout-controls.js
  assets/src/block-editor/components/media-placeholder.js
  assets/src/block-editor/helpers/index.js
  assets/src/block-validation/components/sidebar-notification/index.js
  assets/src/settings-page/plugin-suppression.js
  assets/src/settings-page/supported-templates.js
  bin/amphtml-update.py
Labels: Tech Debt

#6572 Remove obsolete `include_layout_in_wp_kses_allowed_html`
  includes/admin/class-amp-editor-blocks.php
  includes/class-amp-theme-support.php
  tests/php/test-class-amp-theme-support.php
Labels: Tech Debt

#6187 Automate release notes generation
  .github/actions/draft-release/.eslintrc
  .github/actions/draft-release/.gitattributes
  .github/actions/draft-release/README.md
  .github/actions/draft-release/action.yml
  .github/actions/draft-release/dist/index.js
  .github/actions/draft-release/package-lock.json
  .github/actions/draft-release/package.json
  .github/actions/draft-release/src/github.js
  .github/actions/draft-release/src/index.js
  .github/actions/draft-release/src/utils/index.js
  .github/actions/draft-release/src/utils/make_release.js
  .github/workflows/release-draft.yml
  assets/src/customizer/amp-customize-controls.js
  bin/release-changelog/changelog.js
  bin/release-changelog/index.js
  bin/release-changelog/paginate_by_path.js
  package-lock.json
  package.json
Labels: Infrastructure

#6613 Fix flaky E2E test
  tests/e2e/specs/admin/amp-options.js
Labels: Testing

#6543 Convert issue templates into issue forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: Project Management

#6620 Fix E2E tests
  package.json
  tests/e2e/config/bootstrap.js
Labels: Testing

#6625 Fix priorization of TT1 stylesheet after core theme sanitizer changes
  includes/sanitizers/class-amp-style-sanitizer.php
Labels: CSS

#6628 Mark `amp-story-captions` as element containing dynamic content
  includes/sanitizers/class-amp-style-sanitizer.php
Labels: Enhancement, CSS, Integration: Web Stories
