Repository ampproject/amp-wp, pull requests merged in 2021-08, with the labels that each got.

#6504 Update amp-twitter to use fixed-height layout with a default height matching minimal tweet height
  includes/embeds/class-amp-twitter-embed-handler.php
  tests/php/test-amp-twitter-embed-handler.php
Labels: Bento, Embeds

#6436 Update amphtml spec to ed0504b
  includes/sanitizers/class-amp-allowed-tags-generated.php
  tests/php/test-amp-helper-functions.php
  tests/php/test-tag-and-attribute-sanitizer.php
Labels: Validation

#6510 Use customizable `width`/`height` args on `AMP_Twitter_Embed_Handler` rather than literals/defaults
  includes/embeds/class-amp-twitter-embed-handler.php
Labels: Embeds

#6500 Reduce size of UI elements on Settings screen
  assets/src/css/core-components.css
  assets/src/settings-page/style.css
  assets/src/settings-page/welcome.js
Labels: WS:UX

#6518 Experiment: Add native `img` opt-in to prevent conversion to `amp-img`/`amp-anim`
  assets/css/src/amp-default.css
  assets/css/src/amp-playlist-shortcode.css
  includes/amp-helper-functions.php
  includes/class-amp-theme-support.php
  includes/embeds/class-amp-gallery-embed-handler.php
  includes/embeds/class-amp-playlist-embed-handler.php
  includes/sanitizers/class-amp-core-theme-sanitizer.php
  includes/sanitizers/class-amp-gallery-block-sanitizer.php
  includes/sanitizers/class-amp-img-sanitizer.php
  includes/sanitizers/class-amp-style-sanitizer.php
  src/Admin/PairedBrowsing.php
  src/MobileRedirection.php
  tests/php/src/Admin/PairedBrowsingTest.php
  tests/php/src/MobileRedirectionTest.php
  tests/php/test-amp-helper-functions.php
  tests/php/test-amp-img-sanitizer.php
  tests/php/test-class-amp-core-theme-sanitizer.php
  tests/php/test-class-amp-theme-support.php
Labels: Bento

#6527 Add opt-in to prevent `POST` forms from being converted to `amp-form` (with `action-xhr`)
  includes/amp-helper-functions.php
  includes/class-amp-theme-support.php
  includes/sanitizers/class-amp-comments-sanitizer.php
  includes/sanitizers/class-amp-core-theme-sanitizer.php
  includes/sanitizers/class-amp-form-sanitizer.php
  includes/sanitizers/class-amp-gallery-block-sanitizer.php
  includes/sanitizers/class-amp-img-sanitizer.php
  includes/validation/class-amp-validation-error-taxonomy.php
  tests/php/test-amp-form-sanitizer.php
  tests/php/test-amp-helper-functions.php
  tests/php/test-amp-img-sanitizer.php
  tests/php/test-class-amp-comments-sanitizer.php
  tests/php/test-class-amp-core-theme-sanitizer.php
  tests/php/test-class-amp-theme-support.php
Labels: Bento

#6530 Update amphtml spec to dc6cd22a52
  bin/amphtml-update.py
  includes/sanitizers/class-amp-allowed-tags-generated.php
  includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php
  tests/php/test-tag-and-attribute-sanitizer.php
Labels: Validation, Bento

#6353 Add Bento opt-in
  includes/amp-helper-functions.php
  includes/class-amp-theme-support.php
  tests/php/test-amp-helper-functions.php
  tests/php/test-class-amp-theme-support.php
Labels: Bento

#6529 Fix service registration delay causing next service to be skipped
  src/Infrastructure/ServiceBasedPlugin.php
Labels: Bug

#6537 Pass `amp_is_bento_enabled()` to `AMP_Tag_And_Attribute_Sanitizer` as `prefer_bento` arg
  includes/amp-helper-functions.php
Labels: Bento

#6541 Use built-in caching from `actions/setup-node` GHA
  .github/workflows/build-test-measure.yml
  .github/workflows/gutenberg-packages-update.yml
  .nvmrc
Labels: Infrastructure

#6544 [2.1] Use built-in caching from `actions/setup-node` GHA
  .github/workflows/build-test-measure.yml
  .nvmrc
Labels: Infrastructure

#6545 Use class constants instead of classes as string literals
  includes/admin/functions.php
  includes/amp-helper-functions.php
  includes/amp-post-template-functions.php
  includes/class-amp-comment-walker.php
  includes/class-amp-theme-support.php
  includes/templates/class-amp-content-sanitizer.php
  includes/templates/class-amp-content.php
  includes/validation/class-amp-validation-callback-wrapper.php
  includes/validation/class-amp-validation-manager.php
  tests/php/test-amp-helper-functions.php
  tests/php/test-amp-post-template-functions.php
  tests/php/test-class-amp-core-theme-sanitizer.php
  tests/php/test-class-amp-http.php
  tests/php/test-class-amp-link-sanitizer.php
  tests/php/test-class-amp-theme-support.php
  tests/php/test-includes-admin-functions.php
  tests/php/validation/test-class-amp-validated-url-post-type.php
  tests/php/validation/test-class-amp-validation-error-taxonomy.php
  tests/php/validation/test-class-amp-validation-manager.php
Labels: Tech Debt

#6528 Add support for custom non-AMP scripts
  composer.json
  composer.lock
  includes/amp-helper-functions.php
  includes/class-amp-theme-support.php
  includes/sanitizers/class-amp-base-sanitizer.php
  includes/sanitizers/class-amp-script-sanitizer.php
  includes/sanitizers/class-amp-style-sanitizer.php
  includes/validation/class-amp-validation-error-taxonomy.php
  includes/validation/class-amp-validation-manager.php
  tests/php/test-amp-script-sanitizer.php
  tests/php/test-amp-style-sanitizer.php
  tests/php/test-class-amp-base-sanitizer.php
Labels: Bento

#6548 Ensure services that are delayed and have requirements are scheduled correctly
  src/Infrastructure/ServiceBasedPlugin.php
  tests/php/src/Admin/PolyfillsTest.php
  tests/php/src/MobileRedirectionTest.php
Labels: Bug

#6563 Add PostFeaturedImage to PrePublishPanel
  assets/src/block-editor/plugins/pre-publish-panel.js
  assets/src/common/components/higher-order/with-featured-image-notice.js
  assets/src/common/components/pre-publish-panel.js
  assets/src/common/helpers/index.js
  assets/src/common/helpers/test/validateFeaturedImage.js
  package-lock.json
  package.json
  tests/php/test-class-amp-meta-box.php
Labels: Bug, Editor

#6582 Short-circuit `validate_url()` when attempting validation requests to other sites (which will always fail)
  includes/validation/class-amp-validation-manager.php
  tests/php/validation/test-class-amp-validation-manager.php
Labels: Bug, Developer Tools

#6586 Use fixed-height layout for amp-tiktok and add height estimation
  includes/embeds/class-amp-tiktok-embed-handler.php
  tests/php/test-class-amp-tiktok-embed-handler.php
Labels: Embeds
