Repository ampproject/amp-wp, pull requests merged in 2021-02, with the labels that each got.

#5837 Fix test_decorate_shortcode_and_filter_source in WP 5.7-alpha after HTTPS migration commit
  tests/php/validation/test-class-amp-validation-manager.php
Labels: Testing, WS:Core

#5823 Include PreloadHeroImage among transformers omitted for SSR
  includes/class-amp-theme-support.php
Labels: Bug, WS:Perf

#5835 Include sources for validation error formatted data
  includes/validation/class-amp-validated-url-post-type.php
  includes/validation/class-amp-validation-error-taxonomy.php
  tests/php/validation/test-class-amp-validation-error-taxonomy.php
Labels: Integration: WP Core

#5842 Prevent passing empty string as args to RecurringBackgroundTasks
  includes/validation/class-amp-validation-manager.php
  src/BackgroundTask/RecurringBackgroundTask.php
Labels: Bug

#5841 Prevent fatal error when invoking MonitorCssTransientCaching::process() during WP Cron
  includes/validation/class-amp-validation-manager.php
  lib/optimizer/src/Transformer/ServerSideRendering.php
  src/BackgroundTask/MonitorCssTransientCaching.php
Labels: Bug, WS:Core

#5866 Make parameters to Gutenberg filter callbacks more robust
  assets/src/block-editor/components/with-media-library-notice.js
  assets/src/block-editor/helpers/index.js
  assets/src/common/components/higher-order/with-featured-image-notice.js
Labels: Editor, WS:Core

#5870 Use just 'AMP' as plugin sidebar title instead of 'AMP for WordPress'
  assets/src/block-validation/index.js
Labels: WS:Core

#5871 Harden AMP_Post_Type_Support::get_support_errors() to account for case where invalid post is supplied
  includes/admin/class-amp-post-meta-box.php
  includes/class-amp-post-type-support.php
  includes/sanitizers/class-amp-comments-sanitizer.php
  src/Validation/ScannableURLProvider.php
  tests/php/test-class-amp-meta-box.php
  tests/php/test-class-amp-post-type-support.php
Labels: Bug, WS:Core

#5876 Run ESLint on PR fork without generating report
  .github/workflows/build-test-measure.yml
Labels: WS:Core

#5887 Fix misplacement of AMP error count in editor
  assets/src/block-validation/style.css
Labels: Bug, Editor, WS:Core

#5892 Move validation background tasks behind feature flag filter until Site Scanning is implemented
  src/Validation/SavePostValidationEvent.php
  src/Validation/URLValidationCron.php
  tests/php/src/Validation/SavePostValidationEventTest.php
  tests/php/src/Validation/URLValidationCronTest.php
Labels: Site Scanning, WS:Core

#5901 Increase default Jest timeout to 30s
  tests/e2e/config/bootstrap.js
Labels: Testing, WS:Core

#5902 Make AMP_DOM_Utils non-internal since useful for devs and already in third party use
  includes/utils/class-amp-dom-utils.php
Labels: Documentation

#5903 Remove initial-scale=1 meta viewport property by default to disable tap delay
  includes/sanitizers/class-amp-meta-sanitizer.php
  tests/php/test-amp-style-sanitizer.php
  tests/php/test-class-amp-meta-sanitizer.php
Labels: WS:Perf

#5900 Delay showing the unreviewed counts of validated URLs and errors; remove 'At a Glance' widget
  .eslintrc
  .phpstorm.meta.php
  assets/js/amp-service-worker-runtime-precaching.js
  assets/src/amp-validation/counts/index.js
  assets/src/amp-validation/counts/style.css
  includes/validation/class-amp-validated-url-post-type.php
  includes/validation/class-amp-validation-error-taxonomy.php
  src/Admin/ValidationCounts.php
  src/AmpWpPlugin.php
  src/DevTools/UserAccess.php
  src/Validation/ValidationCountsRestController.php
  tests/php/src/Admin/ValidationCountsTest.php
  tests/php/src/OptionsRESTControllerTest.php
  tests/php/src/Validation/ValidationCountsRestControllerTest.php
  tests/php/validation/test-class-amp-validated-url-post-type.php
  tests/php/validation/test-class-amp-validation-error-taxonomy.php
  webpack.config.js
Labels: WS:Perf

#5924 Add support and review links to plugin row meta
  .phpstorm.meta.php
  src/Admin/PluginRowMeta.php
  src/AmpWpPlugin.php
  tests/php/src/Admin/PluginRowMetaTest.php
Labels: WS:Core
