Repository ampproject/amp-wp, pull requests merged in 2021-04, with the labels that each got.

#5955 Inherit object-fit and object-position styles so more conversions work out of the box
  assets/css/src/amp-default.css
  includes/embeds/class-amp-core-block-handler.php
  includes/sanitizers/class-amp-core-theme-sanitizer.php
  includes/sanitizers/trait-amp-noscript-fallback.php
  src/Transformer/DetermineHeroImages.php
  tests/php/src/Transformer/DetermineHeroImagesTest.php
  tests/php/test-amp-audio-converter.php
  tests/php/test-amp-iframe-sanitizer.php
  tests/php/test-amp-img-sanitizer.php
  tests/php/test-amp-script-sanitizer.php
  tests/php/test-amp-style-sanitizer.php
  tests/php/test-class-amp-content-sanitizer.php
  tests/php/test-class-amp-core-block-handler.php
Labels: CSS

#5296 Show error when attempting to validate an AMP-unavailable URL instead of forcing AMP to be available
  includes/amp-helper-functions.php
  includes/class-amp-theme-support.php
  includes/validation/class-amp-validation-manager.php
  tests/php/test-amp-helper-functions.php
  tests/php/test-class-amp-theme-support.php
  tests/php/validation/test-class-amp-validation-manager.php
Labels: WS:Core, cla: yes

#6037 Integrate RewriteAmpUrls transformer from toolbox library
  amp.php
  composer.json
  composer.lock
  includes/class-amp-theme-support.php
  src/ConfigurationArgument.php
  tests/php/test-class-amp-nav-menu-toggle-sanitizer.php
  tests/php/test-class-amp-theme-support.php
Labels: Optimizer, Performance, WS:Perf

#6057 Handle CSS build process with Webpack
  .github/workflows/build-test-measure.yml
  package-lock.json
  package.json
  webpack.config.js
Labels: CSS, Enhancement, WS:UX

#6027 Add status notification to the pre-publish and document sidebar panels
  assets/src/block-editor/plugins/amp-toggle.js
  assets/src/block-editor/plugins/post-status-info.js
  assets/src/block-editor/store/selectors.js
  assets/src/block-editor/store/test/selectors.js
  assets/src/block-validation/components/amp-document-status/index.js
  assets/src/block-validation/components/amp-document-status/test/amp-document-status-notification.js
  assets/src/block-validation/components/amp-toggle/index.js
  assets/src/block-validation/components/amp-toggle/test/amp-toggle.js
  assets/src/block-validation/components/amp-validation-status/index.js
  assets/src/block-validation/components/amp-validation-status/revalidate-notification.js
  assets/src/block-validation/components/amp-validation-status/status-notification.js
  assets/src/block-validation/components/amp-validation-status/test/__snapshots__/revalidate-notification.js.snap
  assets/src/block-validation/components/amp-validation-status/test/__snapshots__/status-notification.js.snap
  assets/src/block-validation/components/amp-validation-status/test/revalidate-notification.js
  assets/src/block-validation/components/amp-validation-status/test/status-notification.js
  assets/src/block-validation/components/sidebar-notification/index.js
  assets/src/block-validation/components/sidebar-notification/style.css
  assets/src/block-validation/components/sidebar-notification/test/__snapshots__/sidebar-notification.js.snap
  assets/src/block-validation/components/sidebar/index.js
  assets/src/block-validation/components/with-amp-toolbar-button/amp-toolbar-button.js
  assets/src/block-validation/hooks/test/use-amp-document-toggle.js
  assets/src/block-validation/hooks/test/use-errors-fetching-state-changes.js
  assets/src/block-validation/hooks/use-amp-document-toggle.js
  assets/src/block-validation/hooks/use-errors-fetching-state-changes.js
  assets/src/block-validation/hooks/use-post-dirty-state-changes.js
  assets/src/block-validation/plugins/amp-block-validation.js
  assets/src/block-validation/plugins/amp-document-setting-panel.js
  assets/src/block-validation/plugins/amp-pre-publish-panel.js
  assets/src/block-validation/store/index.js
  assets/src/block-validation/store/test/store.js
  assets/src/components/loading/style.css
  includes/admin/class-amp-post-meta-box.php
  tests/e2e/specs/block-editor/amp-toggle.js
  tests/js/jest.config.js
Labels: WS:UX

#6065 Turn the AMP Optimizer into an injectable service
  .phpstorm.meta.php
  composer.lock
  includes/class-amp-theme-support.php
  includes/sanitizers/class-amp-core-theme-sanitizer.php
  src/AmpWpPlugin.php
  src/Optimizer/AmpWPConfiguration.php
  src/Optimizer/OptimizerService.php
  src/Optimizer/Transformer/AmpSchemaOrgMetadata.php
  src/Optimizer/Transformer/AmpSchemaOrgMetadataConfiguration.php
  src/Optimizer/Transformer/DetermineHeroImages.php
  tests/php/src/Optimizer/AmpWPConfigurationTest.php
  tests/php/src/Optimizer/OptimizerServiceTest.php
  tests/php/src/Optimizer/Transformer/DetermineHeroImagesTest.php
  tests/php/test-class-amp-schema-org-metadata.php
Labels: Infrastructure, Optimizer, Tech Debt

#6063 Refactor CLI subsystem and add optimize command
  composer.lock
  includes/amp-helper-functions.php
  includes/class-amp-theme-support.php
  includes/cli/class-amp-cli-namespace.php
  src/AmpWpPlugin.php
  src/Cli/AmpCommandNamespace.php
  src/Cli/CommandNamespaceRegistration.php
  src/Cli/OptimizerCommand.php
  src/Cli/TransformerCommand.php
  src/Cli/ValidationCommand.php
  src/Infrastructure/CliCommand.php
  src/Infrastructure/ServiceBasedPlugin.php
  src/Optimizer/Transformer/AmpSchemaOrgMetadataConfiguration.php
  tests/php/test-class-amp-cli-validation-command.php
  tests/php/test-class-amp-theme-support.php
Labels: Infrastructure, Optimizer, WP-CLI

#6062 Improve hero image determination
  .phpstorm.meta.php
  Gruntfile.js
  composer.lock
  includes/sanitizers/class-amp-core-theme-sanitizer.php
  src/AmpWpPlugin.php
  src/Optimizer/AmpWPConfiguration.php
  src/Optimizer/HeroCandidateFiltering.php
  src/Optimizer/Transformer/DetermineHeroImages.php
  tests/php/src/Optimizer/HeroCandidateFilteringTest.php
  tests/php/src/Optimizer/Transformer/DetermineHeroImagesTest.php
  webpack.config.js
Labels: Optimizer, Performance

#6074 Replace Codecov bash uploader with GHA counterpart
  .github/workflows/build-test-measure.yml
Labels: WS:Core

#6081 Bump `codecov/codecov-action` to v1.4.1
  .github/workflows/build-test-measure.yml
Labels: WS:Core

#6067 Update appearance of validation admin tables
  .stylelintrc.json
  assets/css/src/amp-icons.css
  assets/css/src/amp-icons.scss
  assets/css/src/amp-validation-error-taxonomy.css
  assets/css/src/amp-validation-error-taxonomy.scss
  assets/css/src/amp-validation-single-error-url.css
  assets/css/src/components/_amp-stylesheet-list.scss
  assets/css/src/components/_amp-stylesheet-summary.scss
  assets/css/src/components/_details-column.scss
  assets/css/src/components/_error-details-toggle.scss
  assets/css/src/components/_wp-list-table-grid-lines.scss
  assets/css/src/components/_wp-list-table-kept-errors.scss
  assets/css/src/components/_wp-list-table-markup-status-icon.scss
  assets/css/src/components/_wp-list-table-new-errors.scss
  assets/images/amp-valid.svg
  assets/images/down-triangle.svg
  assets/src/amp-validation/amp-validated-url-post-edit-screen.js
  assets/src/amp-validation/amp-validated-urls-index.js
  assets/src/amp-validation/amp-validation-detail-toggle.js
  assets/src/amp-validation/amp-validation-single-error-url-details.js
  assets/src/amp-validation/set-validation-error-rows-classes.js
  assets/src/amp-validation/set-validation-error-rows-seen-class.js
  assets/src/block-validation/components/error/style.css
  includes/validation/class-amp-validated-url-post-type.php
  includes/validation/class-amp-validation-error-taxonomy.php
  src/Icon.php
  tests/php/src/IconTest.php
  tests/php/validation/test-class-amp-validated-url-post-type.php
  tests/php/validation/test-class-amp-validation-error-taxonomy.php
  webpack.config.js
Labels: WS:UX

#6082 Add rel="nofollow noreferrer noopener" to amp-wp.org link in form submission message
  includes/sanitizers/class-amp-form-sanitizer.php
Labels: Sanitizers, WS:Core

#6078 Add Webpack plugin to ignore JS and PHP asset files when stylesheet used as entrypoint
  bin/ignore-extraneous-style-assets.js
  package-lock.json
  package.json
  tests/php/bootstrap.php
  webpack.config.js
Labels: WS:Core

#5859 Disable non-legacy themes selection on Settings screen when AMP slug is defined late
  assets/src/components/amp-setting-toggle/index.js
  assets/src/components/amp-setting-toggle/test/index.js
  assets/src/components/carousel/index.js
  assets/src/components/reader-theme-carousel/index.js
  assets/src/components/reader-theme-carousel/style.css
  assets/src/components/reader-theme-selection/index.js
  assets/src/components/reader-themes-context-provider/index.js
  src/Admin/OptionsMenu.php
  tests/php/src/Admin/OptionsMenuTest.php
Labels: Bug, Reader Mode, WS:UX

#6042 Reader mode: Generate styles for color palette, gradient presets, and font sizes from the theme support features of the primary theme
  .phpstorm.meta.php
  includes/amp-helper-functions.php
  includes/options/class-amp-options-manager.php
  src/AmpWpPlugin.php
  src/Option.php
  src/ReaderThemeLoader.php
  src/ReaderThemeSupportFeatures.php
  tests/php/src/ReaderThemeLoaderTest.php
  tests/php/src/ReaderThemeSupportFeaturesTest.php
  tests/php/test-amp-helper-functions.php
  tests/php/test-amp-render-post.php
Labels: Integration: Gutenberg, WS:Core

#6099 Prevent paired browsing client script from being sanitized
  src/Admin/PairedBrowsing.php
Labels: Bug, WS:Core

#6116 Mark optimizer CLI commands as experimental in their docblock
  src/Cli/OptimizerCommand.php
  src/Cli/TransformerCommand.php
Labels: Documentation, WP-CLI

#6117 Include `OptimizeAmpBind` among transformers omitted for SSR
  src/Optimizer/AmpWPConfiguration.php
  tests/php/src/Validation/URLValidationRESTControllerTest.php
Labels: Bug, WS:Perf

#6118 Display SUMMARY marker by preventing inline display
  assets/src/settings-page/style.css
Labels: Bug, CSS

#6112 Sanitize PDF embeds
  composer.lock
  includes/amp-helper-functions.php
  includes/embeds/class-amp-core-block-handler.php
  includes/sanitizers/class-amp-object-sanitizer.php
  tests/php/test-amp-style-sanitizer.php
  tests/php/test-class-amp-core-block-handler.php
  tests/php/test-class-amp-object-sanitizer.php
Labels: WS:Core

#6122 Hide validation count in menu when on dev tools screen, dev tools is not enabled and Reader mode is enabled
  includes/validation/class-amp-validated-url-post-type.php
  includes/validation/class-amp-validation-error-taxonomy.php
  src/DevTools/UserAccess.php
  tests/php/src/Admin/ValidationCountsTest.php
  tests/php/validation/test-class-amp-validated-url-post-type.php
  tests/php/validation/test-class-amp-validation-error-taxonomy.php
Labels: WS:Core

#6121 Add amp_enable_ssr filter at minimum int so it can be easily overridden
  includes/class-amp-theme-support.php
Labels: Bug, Optimizer

#6119 Fix polyfill dependency issues on WP 4.9
  src/Admin/Polyfills.php
  src/Admin/ValidationCounts.php
  tests/php/src/Admin/PolyfillsTest.php
  webpack.config.js
Labels: WS:Core

#6070 Add feature tests via Behat
  .github/workflows/build-test-measure.yml
  behat.yml
  codecov.yml
  composer.json
  composer.lock
  includes/bootstrap.php
  src/Cli/TransformerCommand.php
  tests/features/optimize-command.feature
  tests/features/optimize-transformer-config-command.feature
  tests/features/optimize-transformer-list-command.feature
  tests/php/maybe-generate-wp-cli-coverage.php
  tests/php/src/Behat/FeatureContext.php
Labels: Infrastructure, Testing

#6125 Support late-defined slugs for paired URL structures and Reader themes
  assets/src/components/reader-theme-carousel/index.js
  assets/src/components/reader-theme-selection/index.js
  assets/src/components/reader-themes-context-provider/index.js
  assets/src/onboarding-wizard/pages/choose-reader-theme/index.js
  includes/amp-helper-functions.php
  includes/class-amp-theme-support.php
  includes/options/class-amp-options-manager.php
  src/Admin/OnboardingWizardSubmenuPage.php
  src/Admin/OptionsMenu.php
  src/Admin/SiteHealth.php
  src/AmpSlugCustomizationWatcher.php
  src/AmpWpPlugin.php
  src/Option.php
  src/PairedRouting.php
  tests/php/src/PairedRoutingTest.php
  tests/php/test-amp-helper-functions.php
  tests/php/test-class-amp-options-manager.php
  tests/php/test-class-amp-theme-support.php
  tests/php/test-class-site-health.php
Labels: Bug

#6148 Update amp-toolbox-php to 0.5.0
  composer.json
  composer.lock
Labels: dependencies
