Repository ampproject/amp-wp, pull requests merged in 2021-03, with the labels that each got.

#5932 Use AMP Settings page URL as 'Close' button link if referrer was login or customizer page
  src/Admin/OnboardingWizardSubmenuPage.php
  src/Admin/OptionsMenu.php
  tests/php/src/Admin/OnboardingWizardSubmenuPageTest.php
Labels: WS:Core

#5937 Escape instances of '</style>' as '<\/style>' in parsed (external) stylesheets
  includes/sanitizers/class-amp-style-sanitizer.php
  tests/php/test-amp-style-sanitizer.php
Labels: Bug, CSS

#5926 Improve handling of Tumblr embeds
  assets/css/src/amp-default.css
  includes/embeds/class-amp-base-embed-handler.php
  includes/embeds/class-amp-tumblr-embed-handler.php
  includes/sanitizers/class-amp-core-theme-sanitizer.php
  tests/php/test-amp-tumblr-embed-handler.php
  tests/php/test-class-amp-core-theme-sanitizer.php
Labels: WS:Core

#5941 Sanitize keys in Server-Timing instead of adding slashes for escaping
  src/Instrumentation/Event.php
  src/Instrumentation/ServerTiming.php
Labels: Bug

#5956 Fix prod build for CI on 2.0 branch
  composer.lock
  tests/php/static-analysis-stubs/wp-cli.php
Labels: WS:Core

#5978 Remove unused images
  assets/images/amp-welcome-icon.svg
  assets/images/editor-help.svg
  assets/images/page-active.svg
  assets/images/page-inactive.svg
  assets/images/quote-black.svg
  assets/images/quote-white.svg
Labels: WS:Core

#5977 2021 theme: Make dark mode selector more specific to override light mode CSS properties
  includes/sanitizers/class-amp-core-theme-sanitizer.php
  tests/php/test-class-amp-core-theme-sanitizer.php
Labels: WS:Core

#5980 Use latest WP image for local env; create database during env setup
  bin/local-env/.env.wp
  bin/local-env/docker-compose.yml
  bin/local-env/includes.sh
  bin/local-env/install-wordpress.sh
  sizereport.config.js
Labels: Infrastructure, WS:Core

#5888 Optimize GHA runtime
  .github/workflows/build-test-measure.yml
  .github/workflows/cancel-previous-runs.yml
Labels: Infrastructure, WS:Core

#5934 Use data-hero-candidate attribute in DetermineHeroImages
  composer.json
  composer.lock
  includes/class-amp-theme-support.php
  includes/sanitizers/class-amp-core-theme-sanitizer.php
  includes/sanitizers/class-amp-meta-sanitizer.php
  includes/utils/class-amp-dom-utils.php
  src/Dom/Options.php
  src/Transformer/DetermineHeroImages.php
  tests/php/src/Transformer/DetermineHeroImagesTest.php
  tests/php/test-amp-carousel.php
  tests/php/test-amp-script-sanitizer.php
  tests/php/test-amp-style-sanitizer.php
  tests/php/test-class-amp-dom-utils.php
  tests/php/test-class-amp-meta-sanitizer.php
  tests/php/test-class-amp-nav-menu-toggle-sanitizer.php
  tests/php/test-class-amp-schema-org-metadata.php
  tests/php/test-class-amp-theme-support.php
  tests/php/test-tag-and-attribute-sanitizer.php
  tests/php/validation/test-class-amp-validation-manager.php
Labels: Integration: WP Core, Optimizer, Performance, WS:Perf

#5996 Eliminate AMP validation from Classic Editor
  includes/validation/class-amp-validation-manager.php
  tests/php/validation/test-class-amp-validation-manager.php
Labels: WS:Core

#5998 Update amphtml spec to 1bbd5505
  bin/amphtml-update.py
  includes/sanitizers/class-amp-allowed-tags-generated.php
  includes/sanitizers/class-amp-img-sanitizer.php
  includes/sanitizers/class-amp-style-sanitizer.php
  includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php
  tests/php/test-amp-img-sanitizer.php
  tests/php/test-amp-style-sanitizer.php
  tests/php/test-tag-and-attribute-sanitizer.php
Labels: Validation, WS:Core

#6026 Update AMP toolbox dependency to 0.3.0
  composer.json
  composer.lock
Labels: Optimizer, dependencies

#6021 Optimize method of stripping validation response of affixed HTML comments
  includes/validation/class-amp-validation-manager.php
  tests/php/validation/test-class-amp-validation-manager.php
Labels: WS:Core
