Repository ampproject/amp-wp, pull requests merged in 2021-12, with the labels that each got.

#6753 Update Gutenberg packages after v12.0.1 release
  package-lock.json
  package.json
Labels: dependencies

#6722 Introduce Bento sanitizer to handle with `bento`-prefixed components
  assets/src/amp-validation/amp-validated-url-post-edit-screen.js
  includes/amp-helper-functions.php
  includes/sanitizers/class-amp-audio-sanitizer.php
  includes/sanitizers/class-amp-base-sanitizer.php
  includes/sanitizers/class-amp-bento-sanitizer.php
  includes/sanitizers/class-amp-iframe-sanitizer.php
  includes/sanitizers/class-amp-img-sanitizer.php
  includes/sanitizers/class-amp-o2-player-sanitizer.php
  includes/sanitizers/class-amp-object-sanitizer.php
  includes/sanitizers/class-amp-playbuzz-sanitizer.php
  includes/sanitizers/class-amp-style-sanitizer.php
  includes/sanitizers/class-amp-video-sanitizer.php
  tests/php/test-amp-audio-converter.php
  tests/php/test-amp-bento-sanitizer.php
  tests/php/test-amp-iframe-sanitizer.php
  tests/php/test-amp-o2-player-sanitizer.php
  tests/php/test-amp-playbuzz-sanitizer.php
  tests/php/test-amp-style-sanitizer.php
  tests/php/test-amp-video-sanitizer.php
  tests/php/test-class-amp-base-sanitizer.php
  tests/php/test-class-amp-object-sanitizer.php
  tests/php/test-tag-and-attribute-sanitizer.php
Labels: P0

#6624 Prevent completely tree-shaken styles from triggering excessive CSS
  includes/sanitizers/class-amp-style-sanitizer.php
  includes/validation/class-amp-validated-url-post-type.php
Labels: Validation, CSS

#6685 Do async site scan on plugin activation instead of synchronous validation
  .eslintrc
  .phpstorm.meta.php
  assets/src/admin/site-scan-notice/index.js
  assets/src/admin/site-scan-notice/notice.js
  assets/src/admin/site-scan-notice/plugins-with-amp-incompatibility.js
  assets/src/admin/site-scan-notice/style.scss
  assets/src/components/amp-admin-notice/index.js
  assets/src/components/amp-admin-notice/style.scss
  assets/src/components/amp-admin-notice/test/__snapshots__/amp-admin-notice.js.snap
  assets/src/components/amp-admin-notice/test/amp-admin-notice.js
  assets/src/components/loading/index.js
  assets/src/components/loading/style.css
  assets/src/components/loading/test/__snapshots__/loading.js.snap
  assets/src/components/loading/test/loading.js
  assets/src/components/site-scan-context-provider/get-slugs-from-validation-results.js
  assets/src/components/site-scan-context-provider/get-sources-from-scannable-urls.js
  assets/src/components/site-scan-context-provider/index.js
  assets/src/components/site-scan-context-provider/test/get-slugs-from-validation-results.js
  assets/src/onboarding-wizard/pages/site-scan/index.js
  assets/src/settings-page/site-scan.js
  includes/validation/class-amp-validation-manager.php
  src/Admin/PluginActivationSiteScan.php
  src/AmpWpPlugin.php
  tests/e2e/config/bootstrap.js
  tests/e2e/specs/admin/after-plugin-activation.js
  tests/e2e/utils/amp-settings-utils.js
  tests/e2e/utils/onboarding-wizard-utils.js
  tests/php/src/Admin/PluginActivationSiteScanTest.php
  tests/php/validation/test-class-amp-validation-manager.php
  webpack.config.js
Labels: Validation, Developer Tools, Site Scanning

#6756 Update to amp-toolbox 0.9.1
  composer.json
  composer.lock
  includes/class-amp-theme-support.php
  includes/embeds/class-amp-base-embed-handler.php
  includes/embeds/class-amp-core-block-handler.php
  includes/embeds/class-amp-gallery-embed-handler.php
  includes/embeds/class-amp-instagram-embed-handler.php
  includes/embeds/class-amp-tiktok-embed-handler.php
  includes/embeds/class-amp-tumblr-embed-handler.php
  includes/embeds/class-amp-youtube-embed-handler.php
  includes/sanitizers/class-amp-accessibility-sanitizer.php
  includes/sanitizers/class-amp-audio-sanitizer.php
  includes/sanitizers/class-amp-bento-sanitizer.php
  includes/sanitizers/class-amp-comments-sanitizer.php
  includes/sanitizers/class-amp-core-theme-sanitizer.php
  includes/sanitizers/class-amp-form-sanitizer.php
  includes/sanitizers/class-amp-gallery-block-sanitizer.php
  includes/sanitizers/class-amp-iframe-sanitizer.php
  includes/sanitizers/class-amp-img-sanitizer.php
  includes/sanitizers/class-amp-link-sanitizer.php
  includes/sanitizers/class-amp-meta-sanitizer.php
  includes/sanitizers/class-amp-o2-player-sanitizer.php
  includes/sanitizers/class-amp-object-sanitizer.php
  includes/sanitizers/class-amp-playbuzz-sanitizer.php
  includes/sanitizers/class-amp-script-sanitizer.php
  includes/sanitizers/class-amp-style-sanitizer.php
  includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php
  includes/sanitizers/class-amp-video-sanitizer.php
  includes/sanitizers/trait-amp-noscript-fallback.php
  includes/utils/class-amp-dom-utils.php
  includes/validation/class-amp-validation-manager.php
  src/Component/Carousel.php
  src/Embed/HandlesGalleryEmbed.php
  src/MobileRedirection.php
  src/Optimizer/HeroCandidateFiltering.php
  src/Optimizer/Transformer/AmpSchemaOrgMetadata.php
  src/Optimizer/Transformer/DetermineHeroImages.php
  src/Sandboxing.php
  tests/php/src/Optimizer/HeroCandidateFilteringTest.php
  tests/php/src/SandboxingTest.php
  tests/php/test-amp-script-sanitizer.php
  tests/php/test-class-amp-comments-sanitizer.php
  tests/php/test-class-amp-theme-support.php
Labels: dependencies

#6758 Fix minor issues with async site scan on plugin activation
  assets/src/components/site-scan-context-provider/index.js
  tests/e2e/specs/admin/after-plugin-activation.js
Labels: Bug, Validation, Site Scanning

#6662 Propagate width/height styles as width/height attributes when setting layout
  includes/sanitizers/class-amp-base-sanitizer.php
  tests/php/test-amp-iframe-sanitizer.php
  tests/php/test-class-amp-base-sanitizer.php
Labels: Sanitizers

#6761 Use intrinsic as default layout for video instead of responsive layout
  includes/sanitizers/class-amp-video-sanitizer.php
  tests/php/test-amp-video-sanitizer.php
  tests/php/test-class-amp-content-sanitizer.php
Labels: Embeds

#6760 Harden access to validation data
  .github/workflows/build-test-measure.yml
  assets/src/admin/site-scan-notice/index.js
  assets/src/components/site-scan-context-provider/index.js
  assets/src/components/site-scan-context-provider/test/site-scan-reducer.js
  assets/src/onboarding-wizard/components/navigation-context-provider.js
  assets/src/onboarding-wizard/index.js
  assets/src/settings-page/index.js
  src/Admin/OnboardingWizardSubmenuPage.php
  src/Admin/OptionsMenu.php
  src/Admin/PluginActivationSiteScan.php
  src/Admin/SupportLink.php
  src/Admin/SupportScreen.php
  tests/e2e/config/bootstrap.js
  tests/e2e/plugins/do-not-allow-amp-validate-capability.php
  tests/e2e/plugins/do-not-allow-amp-validate-capability.zip
  tests/e2e/specs/admin/after-plugin-activation.js
  tests/e2e/specs/admin/site-scan-panel.js
  tests/e2e/specs/amp-onboarding/site-scan.js
  tests/php/src/Admin/OnboardingWizardSubmenuPageTest.php
  tests/php/src/Admin/OptionsMenuTest.php
  tests/php/src/Admin/PluginActivationSiteScanTest.php
  tests/php/src/Admin/SupportLinkTest.php
  tests/php/src/Admin/SupportScreenTest.php
Labels: P0

#6766 Update Gutenberg packages after v12.0.2 release
  package-lock.json
  package.json
Labels: dependencies

#6768 Update `amp-toolbox` to 0.9.2
  composer.json
  composer.lock
Labels: dependencies

#6763 Introduce garbage collection for validation data
  .phpstorm.meta.php
  includes/validation/class-amp-validated-url-post-type.php
  src/AmpWpPlugin.php
  src/BackgroundTask/ValidationDataGarbageCollection.php
  tests/php/src/BackgroundTask/ValidationDataGarbageCollectionTest.php
  tests/php/validation/test-class-amp-validated-url-post-type.php
Labels: Site Scanning

#6769 Ensure `ampify_threaded_comments` runs when in Strict sandboxing
  includes/sanitizers/class-amp-comments-sanitizer.php
  tests/php/test-class-amp-comments-sanitizer.php
Labels: Bug

#6779 Fix selection of Reader theme causing validated URLs to always be stale
  includes/validation/class-amp-validated-url-post-type.php
  tests/php/validation/test-class-amp-validated-url-post-type.php
Labels: Bug, RME

#6780 Remove empty scripts after webpack compilation
  bin/ignore-extraneous-style-assets.js
  package-lock.json
  package.json
  src/Admin/Polyfills.php
  webpack.config.js
Labels: Bug, Infrastructure

#6774 Add screenshots to showcase new UI updates
  .wordpress-org/screenshot-4.png
  .wordpress-org/screenshot-6.png
Labels: Documentation

#6773 Add back-compat to old WP versions for new v2.2 features
  .phpstorm.meta.php
  assets/src/admin/site-scan-notice/index.js
  assets/src/components/plugins-context-provider/index.js
  assets/src/components/site-scan-results/plugins-with-amp-incompatibility.js
  assets/src/components/site-scan-results/themes-with-amp-incompatibility.js
  assets/src/components/themes-context-provider/index.js
  assets/src/onboarding-wizard/index.js
  assets/src/settings-page/index.js
  includes/admin/functions.php
  includes/amp-helper-functions.php
  includes/settings/class-amp-customizer-design-settings.php
  includes/validation/class-amp-validation-manager.php
  src/Admin/AmpPlugins.php
  src/Admin/AmpThemes.php
  src/Admin/OnboardingWizardSubmenuPage.php
  src/Admin/OptionsMenu.php
  src/Admin/PluginActivationSiteScan.php
  src/Admin/SupportLink.php
  src/Admin/SupportScreen.php
  src/AmpWpPlugin.php
  src/DevTools/UserAccess.php
  src/Validation/SavePostValidationEvent.php
  tests/e2e/specs/admin/site-scan-panel.js
  tests/php/src/Admin/AmpPluginsTest.php
  tests/php/src/Admin/AmpThemesTest.php
  tests/php/src/Admin/OnboardingWizardSubmenuPageTest.php
  tests/php/src/Admin/OptionsMenuTest.php
  tests/php/src/Admin/PairedBrowsingTest.php
  tests/php/src/Admin/PluginActivationSiteScanTest.php
  tests/php/src/Admin/SupportScreenTest.php
  tests/php/src/DevTools/UserAccessTest.php
  tests/php/src/Validation/SavePostValidationEventTest.php
  tests/php/src/Validation/URLValidationRESTControllerTest.php
  tests/php/src/Validation/ValidationCountsRestControllerTest.php
  tests/php/test-amp-helper-functions.php
  tests/php/test-class-amp-customizer-design-settings.php
  tests/php/test-class-amp-theme-support.php
  tests/php/validation/test-class-amp-validated-url-post-type.php
  tests/php/validation/test-class-amp-validation-error-taxonomy.php
  tests/php/validation/test-class-amp-validation-manager.php
Labels: P0

#6777 Fix listing of Scannable URLs and re-fetching upon reaching Done step of Onboarding Wizard
  assets/src/components/site-scan-context-provider/index.js
  assets/src/components/site-scan-context-provider/test/site-scan-reducer.js
  assets/src/onboarding-wizard/index.js
  assets/src/onboarding-wizard/pages/done/index.js
  assets/src/onboarding-wizard/pages/done/use-preview.js
  assets/src/settings-page/index.js
  src/Validation/ScannableURLProvider.php
  tests/php/src/Validation/ScannableURLProviderTest.php
Labels: Bug, P0

#6789 Skip Technical Background step if there is no dependency support
  assets/src/onboarding-wizard/components/navigation-context-provider.js
  src/Admin/OnboardingWizardSubmenuPage.php
Labels: Bug, Developer Tools

#6792 Update AMP toolbox to v0.9.3
  composer.json
  composer.lock
Labels: Optimizer

#6791 Ensure site is not scanned multiple times in Onboarding Wizard
  assets/src/components/site-scan-context-provider/index.js
  assets/src/components/site-scan-context-provider/test/site-scan-reducer.js
  assets/src/onboarding-wizard/index.js
Labels: Bug, Changelogged, Site Scanning

#6770 Preload validation counts data if AMP submenu is expanded
  assets/src/amp-validation/counts/index.js
  assets/src/amp-validation/counts/style.css
  includes/validation/class-amp-validated-url-post-type.php
  includes/validation/class-amp-validation-error-taxonomy.php
  src/Admin/ValidationCounts.php
  tests/php/src/Admin/ValidationCountsTest.php
  tests/php/validation/test-class-amp-validated-url-post-type.php
  tests/php/validation/test-class-amp-validation-error-taxonomy.php
Labels: Bug, Validation, P1, Changelogged
