Repository ampproject/amp-wp, pull requests merged in 2021-11, with the labels that each got.

#6673 Update phpstan config for 1.0.0
  .github/workflows/build-test-measure.yml
  phpstan.neon.dist
Labels: Infrastructure

#6666 Update Gutenberg packages after v11.8.0 release
  package-lock.json
  package.json
Labels: dependencies

#6683 Force Standard mode when fetching scannable URLs in Wizard
  assets/src/components/site-scan-context-provider/index.js
  assets/src/onboarding-wizard/__mocks__/amp-settings.js
  assets/src/onboarding-wizard/index.js
  assets/src/onboarding-wizard/pages/done/index.js
  assets/src/onboarding-wizard/setup-wizard.js
  assets/src/settings-page/index.js
  assets/src/settings-page/site-scan.js
  includes/options/class-amp-options-manager.php
  includes/validation/class-amp-validation-manager.php
  src/Admin/OnboardingWizardSubmenuPage.php
  src/Admin/OptionsMenu.php
  src/Admin/SiteHealth.php
  src/QueryVar.php
  src/Validation/ScannableURLProvider.php
  src/Validation/ScannableURLsRestController.php
  tests/e2e/specs/admin/amp-options.js
  tests/e2e/specs/admin/other-settings.js
  tests/e2e/specs/admin/site-review-panel.js
  tests/e2e/specs/admin/site-scan-panel.js
  tests/e2e/specs/amp-onboarding/site-scan.js
  tests/e2e/utils/onboarding-wizard-utils.js
  tests/e2e/utils/site-scan-utils.js
  tests/php/src/Admin/OnboardingWizardSubmenuPageTest.php
  tests/php/src/Admin/OptionsMenuTest.php
  tests/php/src/Admin/SiteHealthTest.php
  tests/php/src/Admin/SupportScreenTest.php
  tests/php/src/Helpers/HomeUrlLoopbackRequestMocking.php
  tests/php/src/Helpers/ThemesApiRequestMocking.php
  tests/php/src/Helpers/ValidationRequestMocking.php
  tests/php/src/Helpers/WithBlockEditorSupport.php
  tests/php/src/Support/SupportDataTest.php
  tests/php/src/Validation/SavePostValidationEventTest.php
  tests/php/src/Validation/ScannableURLProviderTest.php
  tests/php/src/Validation/ScannableURLsRestControllerTest.php
  tests/php/src/Validation/URLValidationCronTest.php
  tests/php/src/Validation/URLValidationProviderTest.php
  tests/php/src/Validation/URLValidationRESTControllerTest.php
  tests/php/test-class-amp-cli-validation-command.php
  tests/php/test-class-amp-reader-themes-rest-controller.php
  tests/php/test-class-amp-youtube-embed-handler.php
  tests/php/validation/test-class-amp-validation-manager.php
Labels: Site Scanning

#6693 Update Gutenberg packages after v11.8.1 release
  package-lock.json
  package.json
  tests/php/test-class-amp-meta-box.php
  tests/php/validation/test-class-amp-validation-manager.php
Labels: dependencies

#6699 Update Gutenberg packages after v11.8.2 release
  package-lock.json
  package.json
Labels: dependencies

#6708 Update Gutenberg packages after v11.8.3 release
  package-lock.json
  package.json
Labels: dependencies

#6705 Do up to 3 validation requests in parallel with a 500 ms delay
  assets/src/components/site-scan-context-provider/index.js
  assets/src/components/site-scan-context-provider/test/site-scan-reducer.js
  assets/src/onboarding-wizard/pages/site-scan/index.js
  assets/src/settings-page/site-scan.js
Labels: Site Scanning

#6713 Revert `package-lock.json` `lockfileVersion` to 1
  package-lock.json
Labels: dependencies

#6716 Update Gutenberg packages after v11.9.0 release
  package-lock.json
  package.json
Labels: dependencies

#6717 Eliminate emoji handling altogether since most browsers now support natively
  includes/class-amp-theme-support.php
  tests/php/test-class-amp-theme-support.php
Labels: Performance

#6680 Mark scripts output by `wp_comment_form_unfiltered_html_nonce()` and `wp_post_preview_js()` as being in AMP Dev Mode
  includes/amp-helper-functions.php
  includes/class-amp-theme-support.php
  tests/php/test-amp-helper-functions.php
  tests/php/test-class-amp-theme-support.php
Labels: Validation

#6719 Update Gutenberg packages after v11.9.0 release
  package-lock.json
  package.json
Labels: dependencies

#6696 Hide recommendations when Site Scan results are stale on Settings screen
  assets/src/components/use-template-mode-recommendation/index.js
  assets/src/components/use-template-mode-recommendation/test/get-template-mode-recommendation.js
  assets/src/onboarding-wizard/pages/template-mode/index.js
  assets/src/settings-page/template-modes.js
  tests/e2e/specs/admin/amp-options.js
  tests/e2e/specs/admin/template-mode.js
  tests/e2e/specs/amp-onboarding/template-mode.js
Labels: Site Scanning

#6698 Improve post Site Scan action items
  assets/src/common/helpers/is-external-url.js
  assets/src/common/helpers/test/is-external-url.js
  assets/src/components/options-context-provider/index.js
  assets/src/components/site-scan-context-provider/index.js
  assets/src/components/site-scan-context-provider/test/site-scan-reducer.js
  assets/src/components/site-scan-results/plugins-with-amp-incompatibility.js
  assets/src/components/site-scan-results/test/site-scan-sources-list.js
  assets/src/components/site-scan-results/themes-with-amp-incompatibility.js
  assets/src/components/use-template-mode-recommendation/index.js
  assets/src/components/use-template-mode-recommendation/test/get-template-mode-recommendation.js
  assets/src/onboarding-wizard/pages/site-scan/index.js
  assets/src/settings-page/site-scan.js
  src/Admin/OptionsMenu.php
  src/Option.php
  src/PluginSuppression.php
  tests/e2e/specs/admin/site-scan-panel.js
  tests/e2e/utils/site-scan-utils.js
  tests/php/src/PluginSuppressionTest.php
Labels: Enhancement, Validation, Site Scanning

#6735 Update Gutenberg packages after v11.9.1 release
  package-lock.json
  package.json
Labels: dependencies

#6745 Update Gutenberg packages after v12.0.1 release
  .nvmrc
  package-lock.json
  package.json
  tests/e2e/specs/admin/site-scan-panel.js
  tests/e2e/specs/amp-onboarding/site-scan.js
Labels: dependencies

#6751 Use Contact Form 7 instead of Autoptimize or Akismet for AMP-incompatible plugin in E2E tests
  tests/e2e/specs/admin/site-scan-panel.js
  tests/e2e/specs/amp-onboarding/site-scan.js
Labels: Infrastructure

#6742 Fix Onboarding Wizard UI glitches
  assets/src/components/template-mode-option/index.js
  assets/src/components/use-template-mode-recommendation/index.js
  assets/src/onboarding-wizard/components/nav/style.css
Labels: Bug

#6743 Do not rescan when going back to Site Scan step in Wizard
  assets/src/components/site-scan-context-provider/__mocks__/index.js
  assets/src/components/site-scan-context-provider/index.js
  assets/src/onboarding-wizard/components/nav/index.js
  assets/src/onboarding-wizard/components/nav/test/index.js
  assets/src/onboarding-wizard/index.js
  assets/src/settings-page/index.js
  tests/e2e/specs/amp-onboarding/site-scan.js
Labels: Bug

#6752 Update amphtml spec to 2111242025000
  includes/sanitizers/class-amp-allowed-tags-generated.php
  tests/php/test-amp-form-sanitizer.php
  tests/php/test-tag-and-attribute-sanitizer.php
Labels: Validation

#6747 Fix and modernize E2E tests
  assets/src/components/site-scan-context-provider/index.js
  assets/src/utils/use-delayed-flag.js
  bin/local-env/docker-compose.yml
  package-lock.json
  package.json
  tests/e2e/config/bootstrap.js
  tests/e2e/jest-ci.config.js
  tests/e2e/jest.config.js
  tests/e2e/plugins/e2e-tests-demo-plugin.php
  tests/e2e/plugins/e2e-tests-demo-plugin.zip
  tests/e2e/specs/admin/amp-options.js
  tests/e2e/specs/admin/other-settings.js
  tests/e2e/specs/admin/site-scan-panel.js
  tests/e2e/specs/admin/template-mode.js
  tests/e2e/specs/amp-onboarding/site-scan.js
  tests/e2e/specs/amp-onboarding/template-mode.js
  tests/e2e/specs/block-editor/amp-preview-button.js
  tests/e2e/specs/block-editor/amp-toggle.js
  tests/e2e/utils/amp-settings-utils.js
  tests/e2e/utils/onboarding-wizard-utils.js
Labels: Infrastructure, Testing
