Repository ampproject/amp-wp, pull requests merged in 2021-01, with the labels that each got.

#5775 Persist URL fragment during client-side mobile redirection and guard against infinite redirect
  assets/src/mobile-redirection.js
Labels: WS:Core

#5729 Remove amp-fit-text block setting
  assets/css/src/amp-block-editor.css
  assets/css/src/amp-default.css
  assets/src/block-editor/helpers/index.js
  assets/src/block-editor/helpers/test/getAmpFitTextContent.js
  assets/src/block-editor/index.js
  includes/admin/class-amp-editor-blocks.php
Labels: Editor, WS:Core

#5777 Harden hash comparison by using hash_equals() instead of ===
  includes/validation/class-amp-validation-manager.php
  tests/php/validation/test-class-amp-validation-manager.php
Labels: Changelogged

#5703 Update amphtml spec to 68e4db07
  bin/amphtml-update.py
  includes/sanitizers/class-amp-allowed-tags-generated.php
  tests/php/test-tag-and-attribute-sanitizer.php
Labels: Changelogged, WS:Core

#5702 [2.0] Update AMP validator spec to 2011140244000…8e02747
  .dev-lib
  assets/src/block-editor/helpers/index.js
  bin/amphtml-update.py
  includes/sanitizers/class-amp-allowed-tags-generated.php
  tests/php/test-tag-and-attribute-sanitizer.php
  tests/php/validation/test-class-amp-validation-manager.php
Labels: Changelogged, WS:Core

#5793 Use wp_robots() instead of noindex() in WP 5.7
  includes/amp-post-template-functions.php
  tests/php/test-amp-post-template-functions.php
Labels: WS:Core

#5558 Add customization of Paired AMP URLs
  .phpstorm.meta.php
  assets/src/admin/paired-browsing/app.css
  assets/src/admin/paired-browsing/app.js
  assets/src/admin/paired-browsing/client.js
  assets/src/block-editor/components/amp-preview-button.js
  assets/src/block-editor/index.js
  assets/src/block-editor/plugins/wrapped-amp-preview-button.js
  assets/src/block-editor/store/selectors.js
  assets/src/block-editor/store/test/selectors.js
  assets/src/settings-page/index.js
  assets/src/settings-page/paired-url-structure.js
  assets/src/settings-page/style.css
  includes/admin/class-amp-post-meta-box.php
  includes/amp-helper-functions.php
  includes/class-amp-theme-support.php
  includes/deprecated.php
  includes/options/class-amp-options-manager.php
  includes/sanitizers/class-amp-comments-sanitizer.php
  includes/sanitizers/class-amp-form-sanitizer.php
  includes/sanitizers/class-amp-link-sanitizer.php
  includes/templates/amp-paired-browsing.php
  includes/validation/class-amp-validated-url-post-type.php
  includes/validation/class-amp-validation-manager.php
  src/Admin/PairedBrowsing.php
  src/AmpWpPlugin.php
  src/MobileRedirection.php
  src/Option.php
  src/OptionsRESTController.php
  src/PairedRouting.php
  src/PairedUrl.php
  src/PairedUrlStructure.php
  src/PairedUrlStructure/LegacyReaderUrlStructure.php
  src/PairedUrlStructure/LegacyTransitionalUrlStructure.php
  src/PairedUrlStructure/PathSuffixUrlStructure.php
  src/PairedUrlStructure/QueryVarUrlStructure.php
  src/PluginSuppression.php
  src/ReaderThemeLoader.php
  tests/e2e/specs/admin/analytics-options.js
  tests/php/src/Admin/PairedBrowsingTest.php
  tests/php/src/DependencyInjectedTestCase.php
  tests/php/src/Fixture/DummyPairedUrlStructure.php
  tests/php/src/MobileRedirectionTest.php
  tests/php/src/OptionsRESTControllerTest.php
  tests/php/src/PairedRoutingTest.php
  tests/php/src/PairedUrlStructure/LegacyReaderUrlStructureTest.php
  tests/php/src/PairedUrlStructure/LegacyTransitionalUrlStructureTest.php
  tests/php/src/PairedUrlStructure/PathSuffixUrlStructureTest.php
  tests/php/src/PairedUrlStructure/QueryVarUrlStructureTest.php
  tests/php/src/PairedUrlStructureTest.php
  tests/php/src/PairedUrlTest.php
  tests/php/src/PluginSuppressionTest.php
  tests/php/src/ReaderThemeLoaderTest.php
  tests/php/static-analysis-stubs/wordpress-defines.php
  tests/php/test-amp-helper-functions.php
  tests/php/test-class-amp-link-sanitizer.php
  tests/php/test-class-amp-meta-box.php
  tests/php/test-class-amp-options-manager.php
  tests/php/test-class-amp-template-customizer.php
  tests/php/test-class-amp-theme-support.php
  tests/php/validation/test-class-amp-validation-manager.php
Labels: WS:Core

#5575 Prevent registration of deprecated AMP blocks that are not used in post
  assets/src/block-editor/index.js
  assets/src/block-editor/store/selectors.js
  assets/src/block-editor/store/test/selectors.js
  includes/admin/class-amp-editor-blocks.php
  includes/admin/class-amp-post-meta-box.php
  tests/php/test-class-amp-meta-box.php
Labels: Editor, WS:Core
