Repository ampproject/amp-wp, pull requests merged in 2021-05, with the labels that each got.

#6168 Prevent page_for_posts from interfering with hero image candidate identification
  src/Optimizer/HeroCandidateFiltering.php
  tests/php/src/Optimizer/HeroCandidateFilteringTest.php
Labels: Bug, Optimizer

#6173 Update toolbox to v0.5.1
  composer.json
  composer.lock
Labels: Bug, dependencies

#6178 Update toolbox to v0.5.2
  composer.json
  composer.lock
Labels: Performance, dependencies

#6181 Prevent fatal error when `amp_*_paired_endpoint()` functions are called before `plugins_loaded` action
  includes/amp-helper-functions.php
Labels: Bug

#6184 Catch exceptions when calling services; prevent service activation/deactivation when disabled
  includes/amp-helper-functions.php
Labels: Bug

#6185 Fix incorrect validation count in admin sidebar
  includes/validation/class-amp-validated-url-post-type.php
  tests/php/src/Validation/ValidationCountsRestControllerTest.php
Labels: Bug

#6197 Account for recursive request parsing in PairedRouting
  src/PairedRouting.php
  tests/php/src/PairedRoutingTest.php
  tests/php/test-class-amp-theme-support.php
Labels: Bug, Routing

#6193 Bump editor support minimum requirements
  src/Editor/EditorSupport.php
  tests/php/src/Editor/EditorSupportTest.php
  tests/php/test-class-amp-meta-box.php
Labels: Editor

#6227 Clarify what Paired URL Structures are and when to change them
  assets/src/settings-page/paired-url-structure.js
  assets/src/settings-page/style.css
Labels: Documentation

#6198 Defer obtaining URL for Customizer preview until AMP Customizer is accessed
  includes/admin/class-amp-template-customizer.php
  includes/admin/functions.php
  includes/amp-post-template-functions.php
  src/QueryVar.php
  tests/php/test-amp-post-template-functions.php
  tests/php/test-class-amp-template-customizer.php
  tests/php/test-includes-admin-functions.php
Labels: Performance

#6253 Fix `lint-js` job failure for dependabot PRs
  .github/workflows/build-test-measure.yml
  .github/workflows/qa-integrate.yml
Labels: Infrastructure

#6254 Fix dependabot username in GHA workflows
  .github/workflows/build-test-measure.yml
  .github/workflows/qa-integrate.yml
Labels: Infrastructure

#6256 Prevent fatal error in HeroCandidateFiltering when attachment post is not available
  src/Optimizer/HeroCandidateFiltering.php
  tests/php/src/Optimizer/HeroCandidateFilteringTest.php
Labels: Bug

#6259 Use last PR commit hash for plugin version code; add query param to cache bust plugin build downloads
  .github/workflows/build-test-measure.yml
  Gruntfile.js
Labels: Infrastructure

#6280 Make E2E env setup more robust; add GHA reporter for E2E and JS unit tests
  bin/local-env/docker-compose.yml
  package-lock.json
  package.json
  tests/e2e/config/bootstrap.js
  tests/e2e/jest.config.js
  tests/js/jest.config.js
Labels: Infrastructure, Testing
