Repository ampproject/amp-wp, pull requests merged in 2021-07, with the labels that each got.

#6446 Update Composer dependencies
  .github/workflows/build-test-measure.yml
  composer.json
  composer.lock
Labels: dependencies, php

#6447 [2.1] Update Composer dependencies
  composer.json
  composer.lock
Labels: dependencies, php

#6464 Add Composer plugin to correctly autoload PHP CSS Parser dependency
  Gruntfile.js
  bin/ci/after-wp-install.sh
  composer.json
  composer.lock
  php-css-parser-install-composer-plugin/composer.json
  php-css-parser-install-composer-plugin/src/Plugin.php
Labels: dependencies, php

#6472 [2.1] Add Composer plugin to correctly autoload PHP CSS Parser dependency
  Gruntfile.js
  bin/ci/after-wp-install.sh
  bin/local-env/install-wordpress.sh
  composer.json
  composer.lock
  php-css-parser-install-composer-plugin/composer.json
  php-css-parser-install-composer-plugin/src/Plugin.php
Labels: dependencies, php

#6476 Pin Gutenberg to v11.0.0 for E2E JS tests
  bin/local-env/install-wordpress.sh
Labels: Testing

#6478 Allow for PR checks to run when a new Gutenberg packages update PR is created
  .github/workflows/gutenberg-packages-update.yml
Labels: Infrastructure

#6482 Change time dependabot creates PRs
  .github/dependabot.yml
Labels: Infrastructure

#6494 Prevent false positive in `redirect_extraneous_paired_endpoint` which needlessly redirects (into infinity)
  src/PairedRouting.php
  tests/php/src/PairedRoutingTest.php
Labels: Routing

#6502 Add overflow buttons to Twitter, Facebook, and Instagram embeds
  includes/embeds/class-amp-base-embed-handler.php
  includes/embeds/class-amp-facebook-embed-handler.php
  includes/embeds/class-amp-instagram-embed-handler.php
  includes/embeds/class-amp-twitter-embed-handler.php
  tests/php/test-amp-facebook-embed-handler.php
  tests/php/test-amp-instagram-embed-handler.php
  tests/php/test-amp-twitter-embed-handler.php
Labels: Bento, Embeds
