Repository ampproject/amp-wp, pull requests merged in 2022-02, with the labels that each got.

#6881 Update Gutenberg packages after v12.5.0 release
  assets/src/admin/amp-plugin-install.js
  assets/src/admin/amp-theme-install.js
  assets/src/admin/site-scan-notice/notice.js
  assets/src/admin/site-scan-notice/plugins-with-amp-incompatibility.js
  assets/src/admin/theme-install/view/theme.js
  assets/src/block-editor/constants.js
  assets/src/block-editor/plugins/wrapped-amp-preview-button.js
  assets/src/block-validation/components/amp-validation-status/test/__snapshots__/status-notification.js.snap
  assets/src/block-validation/store/index.js
  assets/src/components/amp-setting-toggle/test/__snapshots__/index.js.snap
  assets/src/components/clipboard-button/index.js
  assets/src/components/dev-tools-toggle/test/__snapshots__/index.js.snap
  assets/src/components/error-screen/index.js
  assets/src/components/options-context-provider/index.js
  assets/src/components/reader-themes-context-provider/index.js
  assets/src/components/redirect-toggle/test/__snapshots__/redirect-toggle.js.snap
  assets/src/components/site-scan-context-provider/index.js
  assets/src/components/site-scan-results/site-scan-results.js
  assets/src/components/theme-card/index.js
  assets/src/components/user-context-provider/index.js
  assets/src/onboarding-wizard/components/nav/index.js
  assets/src/onboarding-wizard/components/navigation-context-provider.js
  assets/src/onboarding-wizard/index.js
  assets/src/onboarding-wizard/pages/done/index.js
  assets/src/onboarding-wizard/pages/template-mode/screen-ui.js
  assets/src/onboarding-wizard/setup-wizard.js
  assets/src/settings-page/analytics.js
  assets/src/support-page/index.js
  package-lock.json
  package.json
  tests/js/jest.config.js
Labels: dependencies

#6886 [2.2] Update dependencies and fix compatibility with Gutenberg v12.5.0
  assets/src/admin/amp-plugin-install.js
  assets/src/admin/amp-theme-install.js
  assets/src/admin/site-scan-notice/notice.js
  assets/src/admin/site-scan-notice/plugins-with-amp-incompatibility.js
  assets/src/admin/theme-install/view/theme.js
  assets/src/block-editor/constants.js
  assets/src/block-editor/plugins/wrapped-amp-preview-button.js
  assets/src/block-validation/components/amp-validation-status/test/__snapshots__/status-notification.js.snap
  assets/src/block-validation/store/index.js
  assets/src/components/amp-setting-toggle/test/__snapshots__/index.js.snap
  assets/src/components/clipboard-button/index.js
  assets/src/components/dev-tools-toggle/test/__snapshots__/index.js.snap
  assets/src/components/error-screen/index.js
  assets/src/components/options-context-provider/index.js
  assets/src/components/reader-themes-context-provider/index.js
  assets/src/components/redirect-toggle/test/__snapshots__/redirect-toggle.js.snap
  assets/src/components/site-scan-context-provider/index.js
  assets/src/components/site-scan-results/site-scan-results.js
  assets/src/components/theme-card/index.js
  assets/src/components/user-context-provider/index.js
  assets/src/onboarding-wizard/components/nav/index.js
  assets/src/onboarding-wizard/components/navigation-context-provider.js
  assets/src/onboarding-wizard/index.js
  assets/src/onboarding-wizard/pages/done/index.js
  assets/src/onboarding-wizard/pages/template-mode/screen-ui.js
  assets/src/onboarding-wizard/setup-wizard.js
  assets/src/settings-page/analytics.js
  assets/src/support-page/index.js
  composer.json
  composer.lock
  package-lock.json
  package.json
  tests/js/jest.config.js
Labels: dependencies

#6904 Sync dependency updates to 2.2 branch
  .eslintrc
  .github/actions/draft-release/package-lock.json
  assets/src/block-validation/components/error/test/error.js
  assets/src/block-validation/components/with-amp-toolbar-button/test/add-toolbar-button-to-block.js
  assets/src/block-validation/hooks/test/use-amp-document-toggle.js
  assets/src/block-validation/hooks/test/use-errors-fetching-state-changes.js
  assets/src/common/components/with-enforced-file-type.js
  assets/src/components/error-boundary/index.js
  assets/src/components/plugins-context-provider/test/use-normalized-plugins-data.js
  assets/src/components/plugins-context-provider/use-normalized-plugins-data.js
  assets/src/components/themes-context-provider/test/use-normalized-themes-data.js
  assets/src/components/themes-context-provider/use-normalized-themes-data.js
  assets/src/customizer/amp-customizer-design-preview-legacy.js
  composer.json
  composer.lock
  package-lock.json
  package.json
  tests/e2e/specs/admin/after-plugin-activation.js
  tests/e2e/specs/block-editor/amp-toggle.js
Labels: dependencies

#6907 Fix AMP Carousel caption color and position
  .stylelintrc.json
  assets/css/src/amp-default.css
Labels: Bug, Editor

#6910 Update Gutenberg packages after v12.5.4 release
  assets/src/block-validation/components/amp-validation-status/test/__snapshots__/status-notification.js.snap
  assets/src/components/dev-tools-toggle/test/__snapshots__/index.js.snap
  assets/src/components/loading/test/__snapshots__/loading.js.snap
  assets/src/components/template-mode-option/test/__snapshots__/index.js.snap
  package-lock.json
  package.json
Labels: dependencies

#6897 Improve determination of eligible post types for AMP
  includes/class-amp-post-type-support.php
  tests/php/test-class-amp-post-type-support.php
Labels: Enhancement

#6920 Update Gutenberg packages after v12.5.4 release
  package-lock.json
  package.json
Labels: dependencies

#6934 Update Gutenberg packages after v12.6.1 release
  package-lock.json
  package.json
Labels: dependencies

#6900 Re-insert AMP Preview button whenever editor toolbar changes
  assets/src/block-editor/plugins/wrapped-amp-preview-button.js
Labels: Bug, Editor
