Repository ampproject/amp-wp, pull requests merged in 2022-03, with the labels that each got.

#6874 Add dark mode support in twenty twenty-one theme
  includes/admin/class-amp-template-customizer.php
  includes/sanitizers/class-amp-core-theme-sanitizer.php
  includes/sanitizers/class-amp-style-sanitizer.php
  tests/php/test-amp-style-sanitizer.php
  tests/php/test-class-amp-core-theme-sanitizer.php
  tests/php/test-class-amp-template-customizer.php
Labels: Enhancement

#6952 Prevent copying PHP files from `src/` into `assets/`
  webpack.config.js
Labels: Bug, Infrastructure

#6665 Improve handling of WordPress post embeds
  includes/amp-helper-functions.php
  includes/class-amp-theme-support.php
  includes/embeds/class-amp-wordpress-embed-handler.php
  tests/php/test-amp-wordpress-embed-handler.php
  tests/php/test-class-amp-core-block-handler.php
  tests/php/test-class-amp-theme-support.php
  tests/php/validation/test-class-amp-validation-manager.php
Labels: Embeds

#6312 Reduce length of specificity-hacked CSS selectors
  includes/sanitizers/class-amp-style-sanitizer.php
  includes/validation/class-amp-validated-url-post-type.php
  tests/php/test-amp-bento-sanitizer.php
  tests/php/test-amp-script-sanitizer.php
  tests/php/test-amp-style-sanitizer.php
  tests/php/test-class-amp-content-sanitizer.php
  tests/php/test-class-amp-theme-support.php
Labels: CSS

#6803 Update amphtml spec to 2112170012000
  bin/amphtml-update.py
  bin/latest-extension-versions.json
  includes/sanitizers/class-amp-allowed-tags-generated.php
  includes/sanitizers/class-amp-img-sanitizer.php
  includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php
  tests/php/test-amp-img-sanitizer.php
  tests/php/test-amp-style-sanitizer.php
  tests/php/test-tag-and-attribute-sanitizer.php
Labels: P0

#6878 Immediately add/remove DevTools-related AMP admin menu items when setting updated
  assets/src/settings-page/index.js
  src/Admin/OptionsMenu.php
  tests/e2e/specs/admin/anchor-linking.js
Labels: Bug

#6955 Revert #6952 and bump `@wordpress/scripts` to 22.1.0
  package-lock.json
  package.json
  webpack.config.js
Labels: Bug, Infrastructure

#6956 Update amphtml to 2202230359001 and add to latest-extension-versions
  bin/amphtml-update.py
  bin/latest-extension-versions.json
  includes/sanitizers/class-amp-allowed-tags-generated.php
  includes/sanitizers/class-amp-img-sanitizer.php
  tests/php/test-amp-helper-functions.php
  tests/php/test-amp-img-sanitizer.php
  tests/php/test-tag-and-attribute-sanitizer.php
Labels: Validation

#6938 Fix `check_for_page_caching()` to account for `wp_remote_retrieve_header()` returning arrays
  src/Admin/SiteHealth.php
  tests/php/src/Admin/SiteHealthTest.php
Labels: Site Health

#6939 Update `gallery` shortcode embed handler to account for no shortcode attributes
  includes/embeds/class-amp-gallery-embed-handler.php
  tests/php/test-amp-gallery-embed-handler.php
Labels: Bug, Embeds

#6964 Update Dependabot auto-merge workflow based on latest GitHub documentation
  .github/workflows/auto-merge.yml
  .github/workflows/build-test-measure.yml
  .github/workflows/gutenberg-packages-update.yml
Labels: Infrastructure

#6835 Show validation issue for plugin and theme in AMP setting page after site scan.
  .lintstagedrc.js
  assets/src/components/progress-bar/style.scss
  assets/src/components/site-scan-results/data/scannable-urls.js
  assets/src/components/site-scan-results/site-scan-source-list-item.js
  assets/src/components/site-scan-results/site-scan-sources-detail.js
  assets/src/components/site-scan-results/site-scan-sources-list.js
  assets/src/components/site-scan-results/style.scss
  assets/src/components/site-scan-results/test/site-scan-sources-list.js
  assets/src/onboarding-wizard/style.css
Labels: Enhancement

#6933 Add E2E tests for core themes mobile menus
  tests/e2e/config/bootstrap.js
  tests/e2e/specs/core-themes/twentyfifteen.js
  tests/e2e/specs/core-themes/twentyfourteen.js
  tests/e2e/specs/core-themes/twentynineteen.js
  tests/e2e/specs/core-themes/twentyseventeen.js
  tests/e2e/specs/core-themes/twentysixteen.js
  tests/e2e/specs/core-themes/twentythirteen.js
  tests/e2e/specs/core-themes/twentytwelve.js
  tests/e2e/specs/core-themes/twentytwenty.js
  tests/e2e/specs/core-themes/twentytwentyone.js
  tests/e2e/utils/assign-menu-to-location.js
Labels: Testing

#6859 Do async site scan after theme activation
  .phpstorm.meta.php
  assets/src/admin/site-scan-notice/index.js
  assets/src/admin/site-scan-notice/notice.js
  assets/src/admin/site-scan-notice/plugins-with-amp-incompatibility.js
  assets/src/admin/site-scan-notice/style.scss
  assets/src/admin/site-scan-notice/themes-with-amp-incompatibility.js
  assets/src/components/site-scan-results/themes-with-amp-incompatibility.js
  assets/src/components/themes-context-provider/index.js
  assets/src/components/themes-context-provider/test/use-normalized-themes-data.js
  assets/src/components/themes-context-provider/use-normalized-themes-data.js
  src/Admin/AfterActivationSiteScan.php
  src/Admin/OnboardingWizardSubmenuPage.php
  src/Admin/OptionsMenu.php
  src/AmpWpPlugin.php
  tests/e2e/specs/admin/after-plugin-activation.js
  tests/php/src/Admin/AfterActivationSiteScanTest.php
  tests/php/src/Admin/OnboardingWizardSubmenuPageTest.php
  tests/php/src/Admin/OptionsMenuTest.php
Labels: Enhancement, Site Scanning

#6967 Test Twenty Twenty search modal on mobile breakpoint
  tests/e2e/config/bootstrap.js
  tests/e2e/specs/core-themes/twentyfifteen.js
  tests/e2e/specs/core-themes/twentyfourteen.js
  tests/e2e/specs/core-themes/twentynineteen.js
  tests/e2e/specs/core-themes/twentyseventeen.js
  tests/e2e/specs/core-themes/twentysixteen.js
  tests/e2e/specs/core-themes/twentythirteen.js
  tests/e2e/specs/core-themes/twentytwelve.js
  tests/e2e/specs/core-themes/twentytwenty.js
  tests/e2e/specs/core-themes/twentytwentyone.js
  tests/e2e/specs/core-themes/twentytwentytwo.js
  tests/e2e/utils/assign-menu-to-location.js
  tests/e2e/utils/nav-menu-utils.js
Labels: Bug, Testing

#6805 Use native `img` by default
  includes/amp-helper-functions.php
  includes/sanitizers/class-amp-img-sanitizer.php
  includes/sanitizers/class-amp-style-sanitizer.php
  tests/php/test-amp-helper-functions.php
  tests/php/test-amp-img-sanitizer.php
  tests/php/test-amp-style-sanitizer.php
  tests/php/test-class-amp-theme-support.php
Labels: P0

#6975 Attempt to fix Dependabot auto-merge workflow
  .github/workflows/auto-merge.yml
Labels: Infrastructure

#6949 Use `wp_unique_id`-based block class names instead of `uniqid`
  .phpstorm.meta.php
  includes/options/class-amp-options-manager.php
  includes/sanitizers/class-amp-block-uniqid-sanitizer.php
  src/AmpWpPlugin.php
  src/BackgroundTask/MonitorCssTransientCaching.php
  src/BlockUniqidTransformer.php
  tests/php/src/BackgroundTask/MonitorCssTransientCachingTest.php
  tests/php/src/BlockUniqidTransformerTest.php
  tests/php/test-amp-block-uniqid-sanitizer.php
Labels: Bug

#6985 [2.2] Sync dependency updates and more from develop
  .github/workflows/auto-merge.yml
  .github/workflows/build-test-measure.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/gutenberg-packages-update.yml
  .github/workflows/release-draft.yml
  package-lock.json
  package.json
  tests/php/test-amp-style-sanitizer.php
Labels: dependencies

#6894 Add Drop-down for Analytics vendors in AMP setting page.
  assets/src/settings-page/analytics.js
  assets/src/settings-page/style.css
  bin/update-analytics-vendors.js
  includes/ecosystem-data/analytics-vendors.php
  package.json
  src/Admin/OptionsMenu.php
  tests/e2e/specs/admin/analytics-options.js
  tests/php/src/Admin/OptionsMenuTest.php
Labels: Enhancement

#7010 Add margins to buttons on Settings screen
  assets/src/settings-page/style.css
Labels: CSS
