Repository ampproject/amp-wp, pull requests merged in 2022-01, with the labels that each got.

#6824 Update Composer to use AMP toolbox v0.10.0
  .github/workflows/build-test-measure.yml
  composer.json
  composer.lock
Labels: dependencies

#6828 Update Gutenberg packages after v12.3.2 release
  package-lock.json
  package.json
Labels: dependencies

#6841 Update Gutenberg packages after v12.3.2 release
  package-lock.json
  package.json
Labels: dependencies

#6850 Fix test to account for `gutenberg_render_layout_support_flag()`
  tests/php/validation/test-class-amp-validation-manager.php
Labels: Testing

#6846 Ensure validation error `sources` property is always iterable
  assets/src/block-validation/components/error/get-error-source-title.js
  assets/src/block-validation/components/error/test/get-error-source-title.js
  assets/src/block-validation/hooks/use-validation-error-state-updates.js
  assets/src/components/site-scan-context-provider/get-sources-from-scannable-urls.js
  assets/src/components/site-scan-context-provider/test/get-slugs-from-validation-results.js
  includes/validation/class-amp-validation-error-taxonomy.php
Labels: Bug, Site Scanning

#6838 Ampify responsive Navigation Block
  includes/embeds/class-amp-core-block-handler.php
  tests/php/test-class-amp-core-block-handler.php
Labels: Enhancement, Integration: Gutenberg

#6856 Handle case when no scannable URL is available
  assets/src/components/site-scan-context-provider/index.js
  assets/src/components/site-scan-context-provider/test/site-scan-reducer.js
Labels: Bug, Site Scanning

#6833 Remove deprecated controls from editor sidebar and fix AMP Lightbox and AMP Carousel in Gallery block
  assets/css/src/amp-default.css
  assets/src/block-editor/constants.js
  assets/src/block-editor/helpers/index.js
  assets/src/block-editor/helpers/test/AmpLayoutControl.js
  assets/src/block-editor/helpers/test/AmpNoloadingToggle.js
  assets/src/block-editor/helpers/test/addAMPAttributes.js
  includes/embeds/class-amp-core-block-handler.php
  includes/sanitizers/class-amp-gallery-block-sanitizer.php
  src/Embed/HandlesGalleryEmbed.php
  tests/php/test-class-amp-core-block-handler.php
  tests/php/test-class-amp-gallery-block-sanitizer.php
Labels: Bug, Integration: Gutenberg

#6871 Use `block-editor` store name directly to prevent JS errors
  assets/src/block-editor/helpers/index.js
Labels: Bug, Editor
